### ISSUE TITLE
Should have continuous integration

### ISSUE THREAD

**Issue by mafagafogigante** [RuedigerMoeller/fast-serialization#100]
Just now I noticed that a project of this size is not using any kind of CI.

I'd like to set up at least Travis CI to run the tests for pull requests and commits. Any objections @RuedigerMoeller ?

**Comment by mafagafogigante** [comment]
For instance, if my changes to the pom.xml file had broken the maven build, you'd be notified of that in the PR.

**Comment by RuedigerMoeller** [comment]
seems like a good thing. I use testing a lot however I don't run it with each build but manually. I also tend to be sloppy and take my time if some testcases fail :). Its getting particular annoying if there are client server tests and I am mostly too lazy to mock it up ..

Great to learn new things, ignored CI for the most part until now :)

**Comment by mafagafogigante** [comment]
No problem. I just will not set any deadlines on this matters because although I care about this project, it's not my main occupation or hobby.

**Comment by mafagafogigante** [comment]
I have been specially interested in CI solutions to test in environments that you'd struggle to test with.

**Comment by RuedigerMoeller** [comment]
ofc no deadlines & duties .. this is oss :)

**Comment by RuedigerMoeller** [comment]
ca be closed now
