### ISSUE TITLE
Javassist proxies in ArrayList

### ISSUE THREAD

**Issue by vinov** [RuedigerMoeller/fast-serialization#107]
We are testing your (amazing) fast serialization for remoting, passing **hibernate** data and stumbled into a problem with a list of **javassist proxies** created by hibernate. These proxies are handled by `JavassistLazyInitializer` which owns the `target` entity and basically replaces the proxy with the `target` on `writeReplace()`. Finally the client deserializes unproxied entities. 

Now, when there is a list or other collection of proxies, then only the first one is replaced by the target and as a result, deserialized entities are not initialized. 

To simplify this, we tried to simulate this situation in a test, that uses somewhat similar handler. Is it possible to workaround this issue with a custom serializer? 

Thanks, Vit

PS 
Somehow, I could not attach the file, so here is the test:

``` java
import static org.hamcrest.Matchers.instanceOf;
import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertThat;

import java.io.ByteArrayInputStream;
import java.io.Serializable;
import java.lang.reflect.Method;
import java.util.Arrays;
import java.util.Collection;

import javassist.util.proxy.MethodHandler;
import javassist.util.proxy.ProxyFactory;
import javassist.util.proxy.ProxyObject;

import org.junit.Test;
import org.nustaq.serialization.FSTConfiguration;
import org.nustaq.serialization.FSTObjectInput;

public class FstJavassistTest {
  static FSTConfiguration cfg = FSTConfiguration.createDefaultConfiguration();
  static Class proxyClass;

  static {
    ProxyFactory factory = new ProxyFactory();
    factory.setSuperclass(Target.class);
    factory.setInterfaces(new Class[] { Serializable.class, WriteReplace.class });
    proxyClass = factory.createClass();
  }

  @Test
  public void testProxyInArrayList() throws Exception {
    Collection list = Arrays.asList(
            newProxy(new Target("One")),
            newProxy(new Target("Two")),
            newProxy(new Target("Three")));

    Collection result = thereAndBack(list);
    for (Object item : result) {
      System.out.println(item);
      assertThat(item, instanceOf(Target.class));
      assertThat(((Target) item).text, notNullValue());
      assertThat(((Target) item).text, instanceOf(String.class));
    }
  }

  private Target newProxy(final Target target) throws Exception {
    MethodHandler handler = new MyHandler(target);

    Object instance = proxyClass.newInstance();
    ((ProxyObject) instance).setHandler(handler);
    return (Target) instance;
  }

  public Collection thereAndBack(Collection data) throws Exception {
    byte[] buf = cfg.asByteArray(data);
    System.out.println(new String(buf));

    FSTObjectInput objectInput = new FSTObjectInput(new ByteArrayInputStream(buf));
    Collection list = (Collection) objectInput.readObject();
    objectInput.close();
    return list;
  }

  public static class MyHandler implements MethodHandler {
    private Target target;

    public MyHandler(Target target) {
      this.target = target;
    }

    public Target getTarget() {
      return target;
    }

    @Override
    public Object invoke(Object self, Method overridden, Method forwarder, Object[] args) throws Throwable {
      if ("writeReplace".equals(overridden.getName()) && args.length == 0) {
        return target;
      }
      return overridden.invoke(target, args);
    }
  }

  public static class Target implements Serializable {
    private static final long serialVersionUID = 1L;

    public String text;

    public Target() {
    }

    public Target(String text) {
      this.text = text;
    }

    @Override
    public String toString() {
      return text;
    }
  }

  public static interface WriteReplace {
    public Object writeReplace();
  }
}
```

**Comment by belkaram** [comment]
This issue is basically the same as #38. The only difference is that the object read from the stream doesn't have a readResolve method.

**Comment by RuedigerMoeller** [comment]
hi, sorry for delay + thanks for your bug report

* incorrect  handling of proxies inside collections seems to be a bug, i will investigate 

workaround with serializers:

* serializers can be defined on a per class level either single class or class and all subclasses. If you know (or have a) the concrete superclass of your generated proxies, you could workaround the issue using serializers.
* if the solution above is not applicable, you still could try to subclass fstobjectinput/output in order to override object reading and writing. E.g. you can insert custom read write code in case a proxy is detected.

As I am quite busy currently, it might take some time until I can deliver a 'natural' fix for this issue.

**Comment by RuedigerMoeller** [comment]
hm .. the testcase passes for 2.48/2.49 and jdk 1.8_u121
