### ISSUE TITLE
Serializing Path

### ISSUE THREAD

**Issue by Jazzepi** [RuedigerMoeller/fast-serialization#108]
I'm trying to use `Map<Path, Metadata>` in my code because it's the File replacement. Unfortunately it uses `sun.nio.fs.WindowsPath` under the hood on Windows. I've tried to write a custom serializer, but it seems like to me I can only write a serializer when I name the concrete class. Neither AbstractPath or WindowsPath from the sun.nio.fs package are public so I can't name the class files when I go to call registerSerializer(), I can only use Path.class which doesn't work.

I also I thought that using true in the alsoForAllSubclasses would help, but it did not.

Am I missing something, or is it impossible to serialize a private concrete class?

**Comment by RuedigerMoeller** [comment]
registering for Interfaces is not supported, registering for whole class hierarchies is. You might try to register for private classes using `Class.forName()`

**Comment by Jazzepi** [comment]
That worked like a charm. Here's the code I used. Thanks!

            fstConfiguration.registerSerializer(Class.forName("sun.nio.fs.WindowsPath"), new FSTBasicObjectSerializer() {
                @Override
                public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy, int streamPosition) throws IOException {
                    out.writeStringUTF(toWrite.toString());
                }

                @Override
                public Object instantiate(Class objectClass, FSTObjectInput fstObjectInput, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPositioin) throws IOException, ClassNotFoundException, InstantiationException, IllegalAccessException {
                    String stringPath = fstObjectInput.readStringUTF();
                    return Paths.get(stringPath);
                }
            }, false);

**Comment by RuedigerMoeller** [comment]
reopend as FAQ
