### ISSUE TITLE
Cannot find class for code 87

### ISSUE THREAD

**Issue by xamde** [RuedigerMoeller/fast-serialization#109]
I'm trying to migrate from fst 2.24 to fst 2.42. When reading an existing serialised file (this is important for me), the 2.42 gives me the exception "cannot find class for code 87". I understand that fst writes a kind of header, where class names are mapped to integer ids. So I tried to use 2.24 and dump the config, to find what class was mapped to code 87. I found mappings from 3 (String) up to 81 (double[][][][][][][]). So code 87 was either not used or I did not manage to dump it. Reading with 2.24 works fine, but how do I migrate to 2.42? I tried to read the docs and other open issues, but I'm getting lost.

**Comment by RuedigerMoeller** [comment]
these versions are apparently incompatible as I cannot afford the time and effort to test and check compatibility for each old version (its a pretty big matrix).

Workaround:
* read data with old fst version
* write with jdk ser
* switch to new version
* read with JDK
* rewrite with new fst

**Comment by xamde** [comment]
Hi, thanks for the amazingly fast Xmas-timed reply!

Your workaround is nice. My problem is, I'm building download software which is installed on an unknown number of machines already. I need to provide a single download artifact, which can do the migration seamlessly on the remote machine. AFAIK in Java having two versions of the same package (Canonical class names to be exact) does not work. Hmm. I could bundle a kind of shell script with two different classpaths. Another suggestion would be, to change package names for FST whenever a breaking change of the binary format occurs. E.g. have a package org.nusteq.fst.v224.serialisers.

I am slightly surprised that v.2.42 does not read v.2.24 format. Is FST more aimed as an on-the-wire format than a persistence serialisation? I believe, Googles ProtoBuffers also started this way ;-)

When I find a working solution for my issue, I'll post it here.

Finally, a big thanks for FST. Using Java serialization was so painfully slow that my whole app and caching strategy was hopeless. FST was an eye opening improvement. Thanks,

**Comment by RuedigerMoeller** [comment]
probably easier to get the 2.24 code, change the package name and use this to make a conversion
