### ISSUE TITLE
problem deserializing self-referential Array

### ISSUE THREAD

**Issue by bradedelman** [RuedigerMoeller/fast-serialization#112]
```
class FOO implements Serializable {
	FOO()
	{
	}
	FOO[] foos;
}

FOO[] test = new FOO[1];
test[0] = new FOO();
test[0].foos = test;
```
            
test will serialize, but it will fail to deserialize:
`deserialize failed: java.io.IOException: java.io.IOException: unable to ressolve handle 0 <foos of FOO> 111 : 0
`
I'm suspicious of FSTObjectInput.instantiateArray
it calls
objects.registerObjectForRead
only AFTER the array is fully read

FSTObjectInput.readArrayNoHeader also calls objects.registerObjectForRead **but with a pos that has advanced slightly**, so it's not the right handle for the array.

In the previous bug I reported with FSTIdentity2IdMap, my real data leads to an intermittent instance
of this deserialize failure, but only after FSTIdentity2IdMap.resize fails.

In reflecting on the other issue, while it's wrong not to find an already written object (because it got lost by FSTIdentity2IdMap.resize), I still wasn't sure why the resulting data wouldn't deserialize.
It seems like it should deserialize, but have improper extra copies of objects.

That's what led me to this issue.

However, the structure of my data, in the cases that work (most of the time, when the hash function get luckier), I don't understand why the deserializer works, as the same self-references exist.

I need to be sure that my data serializes and deserializes correctly 100% of the time.  I feel pretty certain FSTIdentity2IdMap.resize is broken (see my other post), and it seems like there's at least one more issue with Arrays, but I've only got it 80% understood at this point.

**Comment by RuedigerMoeller** [comment]
your fix to #106 with release 2.44 which is underway to maven.org, will investigate this one asap. Thanks for helping out :)

**Comment by RuedigerMoeller** [comment]
hm, the sample you show above works correctly with fst 2.44 .. can you give a failing testcase ?

**Comment by RuedigerMoeller** [comment]
Stock JDK serialzation has some very weird edge cases (e.g. it implicitely makes assumptions about the structure of the binary streams) such that asymmetric implementation (e.g. write using putFields, read with "defautlReadObject") can lead to invalid stream position computations.

**Comment by bradedelman** [comment]
Thank you so much for your responses.

Thanks for validating and working to fix the issue in FSTIdentity2IdMap.  It was very hard (at least for me) to find, given the intermittent trigger being tied to the Hashes leading to the use of the linear lists in such a subtle way.  I kept thinking it should be more deterministic, and the fact that "playing with memory" could help trigger it, make me think about lost references (too many years of C/C++ in the old days).  

Anyway, when you say: "checked length of lists and none of them exceeds 10 elements, so it seems hashkeys still distribute well."   Are you saying that with my example with the UUID strings, the hashes distribute as expected? Or is there a fix you made?  That is, I think you agreed that sometimes the linear list came into play sooner than expected, and I'm wondering what you did to fix that part.  

Regarding, this issue with the self-referential array, interestingly it seems to only reproduce with the Json serializer.  In our production use, we use the Android serializer, but I'd been experimenting with the Json serializer because it was easier to study the output.  Given that the logic is/should be the same between the output stream types, maybe the issue will shed some light on why it seems to be intermittent as well.

Here's a sample program to try that reproduces the issue for me with the latest fast-serialization code on GitHub:
```
package com.fingerprintplay;

import org.nustaq.serialization.FSTConfiguration;
import org.nustaq.serialization.FSTObjectInput;
import org.nustaq.serialization.FSTObjectOutput;

import java.io.*;

public class Main {

    static class FOO implements Serializable {
        FOO[] foos;
    }

    public static void main(String[] args) throws Exception {
        doTest(FSTConfiguration.createDefaultConfiguration() , "Default");
        doTest(FSTConfiguration.createAndroidDefaultConfiguration(), "Android");
        doTest(FSTConfiguration.createJsonConfiguration(), "Json");
    }

    public static void doTest(FSTConfiguration fstConfiguration, String name) throws Exception
    {
        FOO[] test = new FOO[1];
        test[0] = new FOO();
        test[0].foos = test;

        ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
        FSTObjectOutput out = new FSTObjectOutput(byteArrayOutputStream, fstConfiguration);
        out.writeObject(test);
        out.close(); // required !
        byteArrayOutputStream.close();

        try {
            // deserialize from file using FSTObjectInput - will occasionally fail (because output was corrupt?)
            ByteArrayInputStream byteArrayInputStream = new ByteArrayInputStream(byteArrayOutputStream.toByteArray());
            FSTObjectInput in = new FSTObjectInput(byteArrayInputStream, fstConfiguration);
            Object result = in.readObject();
            in.close(); // required !
            byteArrayInputStream.close();

        } catch (Exception e) {
            System.err.println("deserialize failed: " + e.toString() + " " + name);
        }
    }

}

```

**Comment by bradedelman** [comment]
Thanks again for your help and responses.  I really appreciate it.  Hope you are having a nice weekend.

**Comment by RuedigerMoeller** [comment]
Thank you so much for contributing :). Although fst has >6000 monthly downloads on mvn.org, open source somehow has become a one-way road these days. 
Especially enterprise people show up with a weird mind setting like "if don't add this and that, we won't use it". That's why started to only fix bugs occuring in my commercial work projects for some time .. 
I know the code is kind of hard to understand because its highly optimized, poorly documented and handles a lot of serialization compatibility edge cases one would hardly think of.

As for the JSon issue: Basically currently only JSonNoRef is usable. Reason is, that the higher level part of fst uses the stream position as object handle, which fails for JSon in case it outputs unicode etc. . The Json-with-ref version actually should be removed or fixed.

You shouldn't expect hard bugs in serialization basics as many projects use (defaultConfiguration) fst-serialization (e.g. Apache Wicket, several distributed app frmaeworks, proprietary stuff at Eurex Exchange and other companies). If you go for the lesser used stuff (e.g. JSon), issues are more likely to show up.

**Comment by bradedelman** [comment]
Ok. Awesome. Sure, happy to help!  Your library really helped our project.

The thing that still has me concerned is this: given the resize bug with the hash table, I think objects that were already written get "forgotten" and might get written again. clearly, that's wrong, and clearly it's getting fixed, and with the fix in place, I don't experience any issues.

But while writing out an object a 2nd time is wrong (since the deserialized version won't have a properly shared object), I'm confused as to why it causes the exception I see in the deserializer.. That's what led me to the array question.  Despite the random nature of the hash table issue, the deserialization failure (unable to resolve handle)  is ALWAYS on a type InterpreterData[] so that's why I was studying Arrays.

Hope that question makes sense.

Any thoughts that would help me understand this are greatly appreciated.

**Comment by bradedelman** [comment]
6000 downloads a month - wow!

**Comment by RuedigerMoeller** [comment]
Regarding distribution of hashvalues: My hashmap basically builds up a linked list of HashMaps up to level 5 (currently), after level 5 it degrades to linear search. This workes very well and quick, as I can use very simple hashfucntions for a single hashmap-nodes (btw: only hash collisions lead to a increase of HashMap depth). Once the linear list grow >500, one might try to increase MAX_DEPTH to 7 or so in case this gets an issue

Obviously your data creates a lot of collisions ..

**Comment by RuedigerMoeller** [comment]
regarding your array arguing: 
* I'd assume the issue actually happened at deserialization time (refs where lost, so not found)
* arrays of equal sized objects are very likely to create lots of collisions (=> deep hashmaps) as I am using the stream position as a key and use plain modulo as a hashfunction. Actually each submap should have a different modulo, however if there are lots of objects with identical size, likelyness of hash collisions increases drastically. This is a point which needs future improvement, though it was not an obvious issue in the past ..

**Comment by bradedelman** [comment]
I thought the same thing as you: oh, the same bug must occur during deserialization, but it does not.  For exaple, i f I add this in rePut (instead of the fix):

```
private void rePut(FSTIdentity2IdMap kfstObject2IntMap) {

        // ADD THIS AT THE TOP OF METHOD:
        if ( linearScanList != null ) {
            System.err.println("encountered bug");
        }

```

I can see that I encounter the bug during serialization but **NOT during deserialization.
**   Thus, I'm quite puzzled and I can't quite let it go that there's only the 1 bug during serialization.

The one fact I know for sure is that the deserialization error is 100% of the time on type InterpreterData[], so that's why I dug deeper into Arrays.

Seems the issue reported against JSON streams is a red herring, but I still am suspicious of an error with arrays.

I'm suspicious of FSTObjectInput.instantiateArray
it calls
objects.registerObjectForRead
only AFTER the array is fully read (so if there's a self reference, I'm not sure how it could ever work, though clearly it usually works).  I see that FSTObjectInput.readArrayNoHeader also calls objects.registerObjectForRead but with a pos that has advanced slightly, so it's not the right handle for the array.

I can work more on debugging it, but it'd be super helpful to have input from you on why the registerObjectForRead call in instantiateArray usually works, as I can't quite follow that.

Thanks!

**Comment by RuedigerMoeller** [comment]
hm .. you are right, this looks suspicious, but actually the array is registered in "readArrayNoHeader" so second registerObject is probably unnecessary. However there are several possible paths through this code so the additional registerObject might be required in some scenarios.
This is also inline with successful testcases with self referential arrays.

**Comment by RuedigerMoeller** [comment]
regarding bug occuring on serialization: I use some pretty complicated mechanics to save on hashmap lookups (full graph serialization is all about hashing ..), so it might be the missing values are inflicted inconsistencies at serialization time (see registerForRead() in FSTObjectRegistry ).

**Comment by bradedelman** [comment]
thanks for considering further.

> but actually the array is registered in "readArrayNoHeader"

However, it gets registered at a different "handle" that has advanced a small number of bytes.

If I fix that (pass down the stream position so the register in readArrayNoHeader uses the same number), then the deserialization succeeds (though would be "Wrong" since objects got duplicated instead of shared in my problem case).

**Comment by RuedigerMoeller** [comment]
uh .. will check

**Comment by RuedigerMoeller** [comment]
hm .. from what I see its the same position
```java
    protected Object instantiateArray(FSTClazzInfo.FSTFieldInfo referencee, int readPos) throws Exception {
        Object res = readArray(referencee);
        if ( ! referencee.isFlat() ) {
            objects.registerObjectForRead(res, readPos);
        }
        return res;
    }
```
calls

```java
    protected Object readArray(FSTClazzInfo.FSTFieldInfo referencee) throws Exception {
=>    int pos = getCodec().getInputPos();
        Object classOrArray = getCodec().readArrayHeader();
        if ( classOrArray instanceof Class == false )
            return classOrArray;
        if ( classOrArray == null )
            return null;
=>    Object o = readArrayNoHeader(referencee, pos, (Class) classOrArray);
        getCodec().readArrayEnd(null);
        return o;
    }
```
takes the position in the first line (=same as nothing has been read) and "pos" then moves to the map
```java
    protected Object readArrayNoHeader(FSTClazzInfo.FSTFieldInfo referencee, int pos, Class arrCl) throws Exception {
        final int len = getCodec().readFInt();
        if (len == -1) {
            return null;
        }
        Class arrType = arrCl.getComponentType();
        if (!arrCl.getComponentType().isArray()) {
            Object array = Array.newInstance(arrType, len);
            if ( ! referencee.isFlat() )
=>              objects.registerObjectForRead(array, pos );
            if (arrCl.getComponentType().isPrimitive()) {
                return getCodec().readFPrimitiveArray(array, arrType, len);
            } else { // Object Array
                Object arr[] = (Object[]) array;
                for (int i = 0; i < len; i++) {
                    Object value = readObjectWithHeader(referencee);
                    value = getCodec().coerceElement(arrType, value);
                    arr[i] = value;
                }
                getCodec().readObjectEnd();
            }
            return array;
        } else { // multidim array
            Object array[] = (Object[]) Array.newInstance(arrType, len);
            if ( ! referencee.isFlat() ) {
                objects.registerObjectForRead(array, pos);
            }
            FSTClazzInfo.FSTFieldInfo ref1 = new FSTClazzInfo.FSTFieldInfo(referencee.getPossibleClasses(), null, clInfoRegistry.isIgnoreAnnotations());
            for (int i = 0; i < len; i++) {
                Object subArray = readArray(ref1);
                array[i] = subArray;
            }
            return array;
        }
    }
```

**Comment by RuedigerMoeller** [comment]
argh .. got it. instantiateArray's "readPos" is some bytes behind and should be passed to "readArray".

Good find. Thanks a lot !!

**Comment by bradedelman** [comment]
Awesome. Cool. So glad I was able to communicate that. 

So the final piece of the puzzle that I can't figure out is why I encounter that deserialization issue with arrays only when I encounter the serialization issue with the hash map. 

That has me baffled.

**Comment by bradedelman** [comment]
I'm on the train right now. When I'm at the office I'll sent you the read array change I made, just for comparisons sake. Should've sent it with my comment earlier. Sorry about that.

**Comment by RuedigerMoeller** [comment]
you can also simply clone my repository and create a pull request .. I'll run my testsuite before releasing then.

**Comment by RuedigerMoeller** [comment]
you might also want to star this wonderful project ;)

**Comment by bradedelman** [comment]
sure! I've starred it. sorry, didn't even realize that was a thing...

**Comment by RuedigerMoeller** [comment]
most people stick close to the herd, that's why its kind of a thing ;)

**Comment by bradedelman** [comment]
pull request created - with notes.
thanks.
