### ISSUE TITLE
Unable to deserialize unmodifiable collections from JSON

### ISSUE THREAD

**Issue by jkubrynski** [RuedigerMoeller/fast-serialization#114]
When trying to deserialize unmodifiable collection from JSON FST throws an exception:
`java.lang.RuntimeException: cannot support legacy JDK serialization methods in crossplatform mode. Define a serializer for this class java.util.Collections$UnmodifiableRandomAccessList`

**Comment by RuedigerMoeller** [comment]
need to add this to JSON config only as it breaks things for other configurations (unmodifiable work fine with default-non-json serialization)

**Comment by RuedigerMoeller** [comment]
fixed with 2.46
