### ISSUE TITLE
What is the minimum JRE version required to use FST?

### ISSUE THREAD

**Issue by eduardo-ostertag** [RuedigerMoeller/fast-serialization#118]
I downloaded the lastest versión of FST (**2.44**) that I am using in a project built using **JRE 1.7**. When I executed my ANT script I got the following **javadoc** message:

[javadoc] warning: ...\fst-2.44-onejar.jar(org/nustaq/serialization/FSTConfiguration.class): major version 52 is newer than 51, the highest major version supported by this compiler.

Before version **2.44** **javadoc** did not complain. So my question is: **what is the minimum JRE version required to use FST? 1.6, 1.7 or 1.8?** 

My apologies if this is documented somewhere in this repository. I search for this information, and I could not find an answer.

**Comment by RuedigerMoeller** [comment]
fst is fully compatible to jdk 1.7, it seems like the downloadable build somehow includes/compile with 1.8.
Workaround: use the version published on maven.org for a 1.7 compatible build.

There seems to be an issue with the creation of the downloadable fat-jar.

**Comment by eduardo-ostertag** [comment]
Thank you very much. I'll wait for the new downloadable fst-jar compiled for jdk 1.7

**Comment by RuedigerMoeller** [comment]
checked back and the gradle build used for the downloadable artifacts is set to 1.7 source compatibility ..

**Comment by RuedigerMoeller** [comment]
you might want to have a lok at it https://github.com/RuedigerMoeller/fast-serialization/blob/master/build.gradle

**Comment by eduardo-ostertag** [comment]
Sorry, but I know nothing about **graddle**. Ant task **javadoc** is telling me that the classes:

**org.nustaq.serialization.FSTConfiguration**
**org.nustaq.serialization.simpleapi.DefaultCoder**

are compiled with a compiler **versión 52**. The specific warning messages I get are the following:

**[javadoc]** warning: fst-2.44-onejar.jar(org/nustaq/serialization/FSTConfiguration.class): major version 52 is newer than 51, the highest major version supported by this compiler.
**[javadoc]** warning: fst-2.44-onejar.jar(org/nustaq/serialization/simpleapi/DefaultCoder.class): major version 52 is newer than 51, the highest major version supported by this compiler.

**Comment by eduardo-ostertag** [comment]
I just downloaded versión **2.45** of FST. I extracted the file "**DefaultCoder.class**" from the file "**fst-2.45-onejar.jar**", and then executed the following command in a **Windows** platform:

**javap -verbose DefaultCoder | findstr "major"**

the output of this command was:

**Warning: Binary file DefaultCoder contains org.nustaq.serialization.simpleapi.DefaultCoder
  major version: 52**

The same happened with the files "**FSTClazzInfo.class**" and "**FSTConfiguration.class**". My guess is that the same will happend with all your *.class files. 

**Any idea why your code is compiled with a Java 1.8 compiler?**

**Comment by RuedigerMoeller** [comment]
no idea, actually the gradly build explicitely define target 1.7 .. strange, I might drop gradle and create fat jars using maven ..
