### ISSUE TITLE
FSTBasicObjectSerializer subclass failing

### ISSUE THREAD

**Issue by cogmission** [RuedigerMoeller/fast-serialization#123]
I have a class Called `DateEncoderSerializer` which extends `FSTBasicObjectSerializer`
My intention is to set the `DateTimeFormatter` (Joda) on it before returning the DateEncoder object, since DateTimeFormatter doesn't implement Serializable.

I marked the relevant DateTimeFormatter fields in my DateEncoder class as "transient", which allows the DateEncoder to be successfully serialized/deserialized when no Serializer is registered with the `FSTConfiguration` object. However, of course my field is uninitialized because I have to set it to be "transient" to avoid exceptions.

When I register the Serializer: 

``` Java
fastSerialConfig.registerSerializer(DateEncoder.class, new DateEncoderSerializer(), false);
```

I get the following stack trace?

I've tried multiple variations of out.writeObject(...), out.defaultWriteObject(...) in combination with the associated in.readXXX() methods and I keep getting Exceptions?

Like I said, without the registration, the DateEncoder object serializes/deserializes fine but I need to be able to set the `DateTimeFormatter` on it before it is usable??

Any ideas why the out/in write/read methods are failing? 
# 

java.io.IOException: java.lang.NullPointerException
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
    at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1122)
    at org.numenta.nupic.network.NetworkSerializerImpl.deSerialize(NetworkSerializerImpl.java:142)
    at org.numenta.nupic.network.JavaFstNetworkSerializationTest.testHTMSensor(JavaFstNetworkSerializationTest.java:498)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:353)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
    at org.nustaq.serialization.FSTObjectInput.readObjectFields(FSTObjectInput.java:708)
    at org.nustaq.serialization.FSTObjectInput.instantiateAndReadNoSer(FSTObjectInput.java:562)
    at org.nustaq.serialization.FSTObjectInput.readObjectWithHeader(FSTObjectInput.java:370)
    at org.nustaq.serialization.FSTObjectInput.readObjectInternal(FSTObjectInput.java:327)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:307)
    at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:241)
    ... 26 more

**Comment by cogmission** [comment]
Here's my DateEncoderSerializer class:

```Java
public class DateEncoderSerializer extends FSTBasicObjectSerializer {
    
    @Override
    public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTFieldInfo referencedBy, int streamPosition) throws IOException {
        // TODO Auto-generated method stub
        System.out.println("DateEncoderSerializer Reached writeObject");
        out.writeObject(toWrite);
//        out.flush();
//        out.close();
    }
    
    @Override
    public void readObject(FSTObjectInput in, Object toRead, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy) throws Exception {
        System.out.println("DateEncoderSerializer Reached readObject() with: " + toRead);
        String customFormatPattern = ((DateEncoder)toRead).getCustomFormatPattern();
        if(customFormatPattern != null) {
            // Do my work here if things go ok
        }
    }
    
    @SuppressWarnings("rawtypes")
    @Override
    public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPosition) throws Exception {
        System.out.println("DateEncoderSerializer Reached instantiate()");
//        DateEncoder de = DateEncoder.builder().build();
//        in.defaultReadObject(referencee,serializationInfo,de);
//        Object obj = in.readObject();
//        Object res = in.readObject();
        
        return null;
    }

}
```

**Comment by cogmission** [comment]
I have a feeling I'm going to have to be able to use this Serializer registration idiom many times before my project is fully serializable - so if you can help me solve this and maybe give me some "rules of thumb" for how to use this subclass, it would be really helpful?

Thanks very much! And I was able to get much further with your code than with Kryo, so I'd like to continue using it if possible :-)

**Comment by RuedigerMoeller** [comment]
hi, serializers are used internally a lot (just check the source), so its likely you are doing something wrong or I did not document it accordingly. I'll check back tomorrow. Have fun :). Usually it is not be that hard to get stuff serializable as fst can use existing implementations of libraries/JDK

**Comment by RuedigerMoeller** [comment]
pls provide a full sample of your failure as frequently the bug is already in the outer use (invalid stream handling and stuff)

**Comment by RuedigerMoeller** [comment]
or at leat give a snippet constructing the object yu want to serialize ..

**Comment by cogmission** [comment]
Here's a Gist of the object I am Serializing...

I hope this helps but, you'll need to get the dependencies - that's why I didn't bother sending it... Like I said it serializes fine when not using the FSTBasicObjectSerializer...? ...and it hangs on the Read and not the Write (see the stack trace)

https://gist.github.com/cogmission/e9e0de02e606fe026372

It's instantiated by DateEncoder.Builder().build();

**Comment by cogmission** [comment]
Can you give me an example of using this Object Serializer with a simple object? Using both write/readObject and defaultWrite/ReadObject - altering the serialized object at both the instantiate() method and the readObject() methods of the Object Serializer?

**Comment by cogmission** [comment]
If you are determined I can give you instructions for downloading my project, and then give you a test class to run the problem - that way you can get the exact environment - if you have that time?

**Comment by cogmission** [comment]
Ok, I've distilled the code down to a manageable group of classes you can use to duplicate a closely related issue which is that the inner objects aren't being written or read (null when object is deserialized) - which I think is related to the above issue... Maybe if you can point me to what I'm doing wrong here, I can figure out the rest? I'm giving you the test method and 4 classes which you can put in your own packages and run - it should demonstrate that the inner object inside the container object is null when the object is deserialized.

See attached jar (zip) for supporting classes...

```Java
@Test
    public void testObjectSerializersPureFST() {
        FSTConfiguration cnf = FSTConfiguration.createDefaultConfiguration();
        cnf.registerSerializer(TestSerializeContainer.class, new TestSerializeContainerSerializer(), false);
        
        SerialConfig config = new SerialConfig("testObjectSerializersPureFST", Scheme.FST);
        
        TestSerializeContainer tsc = new TestSerializeContainer();
        tsc.setMinMax(new MinMax());
        
        //////////////////////////
        //    Write Object      //
        //////////////////////////
        
        // Setup target path
        String path = System.getProperty("user.home") + File.separator + "HTMNetwork";
        File customDir = new File(path);
        customDir.mkdirs();
        
        File serialPath = new File(customDir.getAbsolutePath() + File.separator +  config.getFileName());
        
        byte[] bytes = cnf.asByteArray(tsc);
        try {
            if(!serialPath.exists()) {
                serialPath.createNewFile();
            }
            
            Files.write(serialPath.toPath(), bytes, config.getOpenOptions());
        } catch(IOException e) {
            e.printStackTrace();
        }
        
        //////////////////////////
        //     Read Object      //
        //////////////////////////
        
        TestSerializeContainer serializedContainer = null;
        try {
            bytes = Files.readAllBytes(serialPath.toPath());
            serializedContainer = (TestSerializeContainer)cnf.asObject(bytes);
        } catch(IOException e) {
            throw new RuntimeException(e);
        }
    
        System.out.println("inner = " + serializedContainer.getMinMax());
        
    }
```

[fourclasses.zip](https://github.com/RuedigerMoeller/fast-serialization/files/182765/fourclasses.zip)

**Comment by cogmission** [comment]
@RuedigerMoeller Ok That's as far as I can take you - now the ball's in your court :-)  Thanks a lot, because I really need this!

**Comment by cogmission** [comment]
@RuedigerMoeller Also tried this (using FSTObjectIn/Output):

```Java
@Test
    public void testObjectSerializersFSTStreams() {
        FSTConfiguration cnf = FSTConfiguration.createDefaultConfiguration();
        cnf.registerSerializer(TestSerializeContainer.class, new TestSerializeContainerSerializer(), false);
        
        SerialConfig config = new SerialConfig("testObjectSerializersPureFST", Scheme.FST);
        
        TestSerializeContainer tsc = new TestSerializeContainer();
        tsc.setMinMax(new MinMax());
        
        //////////////////////////
        //    Write Object      //
        //////////////////////////
        
        // Setup target path
        String path = System.getProperty("user.home") + File.separator + "HTMNetwork";
        File customDir = new File(path);
        customDir.mkdirs();
        
        File serialPath = new File(customDir.getAbsolutePath() + File.separator +  config.getFileName());
        
        try {
            if(!serialPath.exists()) {
                serialPath.createNewFile();
            }
            
            FileOutputStream stream = new FileOutputStream(serialPath);
            FSTObjectOutput out = cnf.getObjectOutput(stream);
            out.writeObject(tsc, TestSerializeContainer.class);
            // DON'T out.close() when using factory method;
            out.flush();
            stream.close();
        } catch(IOException e) {
            e.printStackTrace();
        }
        
        //////////////////////////
        //     Read Object      //
        //////////////////////////
        
        TestSerializeContainer serializedContainer2 = null;
        try {
            FileInputStream stream = new FileInputStream(serialPath);
            FSTObjectInput in = cnf.getObjectInput(stream);
            serializedContainer2 = (TestSerializeContainer)in.readObject(TestSerializeContainer.class);
        } catch(Exception e) {
            throw new RuntimeException(e);
        }
    
        System.out.println("inner = " + serializedContainer2.getMinMax());
        
    }
```

**Comment by cogmission** [comment]
If you comment out this (2nd) line : cnf.registerSerializer(TestSerializeContainer.class, new TestSerializeContainerSerializer(), false);

You'll see the inner object is serialized/deserialized fine... So there 's something going on with the FSTObjectSerializer methods..?

**Comment by cogmission** [comment]
Are you there? Please help? :-)

**Comment by cogmission** [comment]
Did some digging, and it seems that the writeObject() method never calls writeFields() when a FSTObjectSerializer is involved?

**Comment by RuedigerMoeller** [comment]
I'll try to reproduce

**Comment by cogmission** [comment]
@RuedigerMoeller Thank you! :-)  Actually I see no examples of FSTObjectSerializers being used as external serializers anywhere in the code? WriteFields does not get called for externals it seems?

**Comment by RuedigerMoeller** [comment]
if a serializer is installed, serialization is completely delegated

**Comment by RuedigerMoeller** [comment]
your serializer implementation makes no sense to me. Just calling writeObject does not make an object serializable all of a sudden ..

**Comment by cogmission** [comment]
How does one use FST to implement the "complete" serialization? What methods are necessary to call? I'm doing this to be able to install transient fields which are necessary so all I want to do is serialize/deserialize, then configure the transient fields = so how do I do that - what methods do I call to use FST to serialize and deserialize?

**Comment by cogmission** [comment]
@RuedigerMoeller 

Is that clear? What I need to know is how to use the write/read/instantiate methods of the FSTObjectSerializer to do "normal" serialization/deserialization for those classes that have transient fields which I need to "manually" configure following deserialization?

**Comment by RuedigerMoeller** [comment]
can you give me the exact maven dependencies ? I need the trove version and joda version in order to compile. You snippets do not match the newest trove version (1.1beta-5)

**Comment by cogmission** [comment]
Ok one sec.

**Comment by cogmission** [comment]
Hi @RuedigerMoeller How's it going?

**Comment by cogmission** [comment]
@RuedigerMoeller Please let me know if you are working on this or not? I'm watching this page like TV :-P  If you are working on this on the side of a job and you don't have much time, I understand - I just need to know what's going on?

**Comment by cogmission** [comment]
@RuedigerMoeller Any news?

**Comment by RuedigerMoeller** [comment]
as my job porject is also on github i miss messages in the flood of notifications ..
will try to find some time this weekend ..

**Comment by cogmission** [comment]
@RuedigerMoeller Thank you very much!

**Comment by cogmission** [comment]
@RuedigerMoeller Never mind, I moved on... Thanks.

**Comment by RuedigerMoeller** [comment]
sorry, I am too busy to help out. Just try reading the documentation, you can be sure the serializers work correctly as they are a fundamental concept of fst used many time .., so its actually not a fst issue but a lack of understanding on your side ;)

**Comment by cogmission** [comment]
What you do in your serializers isn't the same thing I'm trying to do. Nobody's too busy to give one simple example of what I'm trying to do, especially when they're familiar with the code? Pitiful...

**Comment by RuedigerMoeller** [comment]
I'll give it a second look .. as I find time, we're going to beta soon, no time ..

**Comment by RuedigerMoeller** [comment]
just look at the source, there are many examples for serializers:

![image](https://cloud.githubusercontent.com/assets/6097932/14142496/66be5a8a-f686-11e5-949b-7fa6fa661c22.png)

example for complete serialization:
```java
public class FSTStringBufferSerializer extends FSTBasicObjectSerializer {
    @Override
    public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy, int streamPosition) throws IOException {
        out.writeStringUTF(toWrite.toString()); // cruel slow stuff
    }

    /**
     * @return true if FST can skip a search for same instances in the serialized ObjectGraph. This speeds up reading and writing and makes
     *         sense for short immutable such as Integer, Short, Character, Date, .. . For those classes it is more expensive (CPU, size) to do a lookup than to just
     *         write the Object twice in case.
     */
    @Override
    public boolean alwaysCopy() {
        return false;
    }

    @Override
    public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPosition) throws Exception {
        String s = in.readStringUTF();
        StringBuffer stringBuffer = new StringBuffer(s);
        in.registerObject(stringBuffer, streamPosition, serializationInfo, referencee);
        return stringBuffer;
    }
}
```

in order to invoke the default write method just use `public void defaultWriteObject(Object toWrite, FSTClazzInfo serializationInfo)` method of `FSTObjectOutput`.

**Comment by RuedigerMoeller** [comment]
you have to symmetrically use defaultReadObject at read time.

**Comment by RuedigerMoeller** [comment]
> Is that clear? What I need to know is how to use the write/read/instantiate methods of the FSTObjectSerializer to do "normal" serialization/deserialization for those classes that have transient fields which I need to "manually" configure following deserialization?

same as with stock JDK serialization: use defuaultReadObject and defaultWriteObject. You cannot invoke readObject/writeObject directly (same as JDK serialization)..

**Comment by cogmission** [comment]
Thank you. I saw all those serializers and they all serialize known types. None of them do complex types - which was of no help to me... And there was no documentation as to how to use these serializers with complex pojos. The example you give above uses a String... 

I tried using the defaultWrite/ReadObject pair and got exceptions... I will give it another try... 

Now see that wasn't so bad was it? ;-)

Thanks again...

**Comment by RuedigerMoeller** [comment]
there are also examples for complex types
```java
public class FSTCollectionSerializer extends FSTBasicObjectSerializer {

    @Override
    public void writeObject(FSTObjectOutput out, Object toWrite, FSTClazzInfo clzInfo, FSTClazzInfo.FSTFieldInfo referencedBy, int streamPosition) throws IOException {
        Collection col = (Collection)toWrite;
        int size = col.size();
        out.writeInt(size);
        Class lastClz = null;
        FSTClazzInfo lastInfo = null;
        if ( col.getClass() == ArrayList.class ) {
            List l = (List) col;
            for (int i = 0; i < size; i++) {
                Object o = l.get(i);
                if ( o != null ) {
                    lastInfo = out.writeObjectInternal(o, o.getClass() == lastClz ? lastInfo : null, null);
                    lastClz = o.getClass();
                } else
                    out.writeObjectInternal(o, null, null);
            }
        } else
        {
            for (Object o : col) {
                if ( o != null ) {
                    lastInfo = out.writeObjectInternal(o, o.getClass() == lastClz ? lastInfo : null, null);
                    lastClz = o.getClass();
                } else
                    out.writeObjectInternal(o, null, null);
            }
        }
    }

    @Override
    public Object instantiate(Class objectClass, FSTObjectInput in, FSTClazzInfo serializationInfo, FSTClazzInfo.FSTFieldInfo referencee, int streamPosition) throws Exception {
        try {
            Object res = null;
            int len = in.readInt();
            if ( objectClass == ArrayList.class ) {
                res = new ArrayList(len);
            } else
            if ( objectClass == HashSet.class ) {
                res = new HashSet(len);
            } else
            if ( objectClass == Vector.class ) {
                res = new Vector(len);
            } else
            if ( objectClass == LinkedList.class ) {
                res = new LinkedList();
            } else {
                if ( AbstractList.class.isAssignableFrom(objectClass) && objectClass.getName().startsWith( "java.util.Arrays" ) ) {
                    // some collections produced by JDK are not properly instantiable (e.g. Arrays.ArrayList), fall back to arraylist then
                    res = new ArrayList<>();
                } else {
                    res = objectClass.newInstance();
                }
            }
            in.registerObject(res, streamPosition,serializationInfo, referencee);
            Collection col = (Collection)res;
            if ( col instanceof ArrayList ) {
                ((ArrayList)col).ensureCapacity(len);
            }
            for ( int i = 0; i < len; i++ ) {
                final Object o = in.readObjectInternal(null);
                col.add(o);
            }
            return res;
        } catch (Throwable th) {
            FSTUtil.<RuntimeException>rethrow(th);
        }
        return null;
    }
}
```

well, open source does not pay my bills, its fine if I get error reports as this improves FST, its getting problematic once I am actually doing consulting for free ..

**Comment by cogmission** [comment]
> well, open source does not pay my bills, its fine if I get error reports as this improves FST, its getting problematic once I am actually doing consulting for free ..  

Point taken. However, open source does contribute indirectly to your overall "employability" and stature... However I understand your point...

Thank you for the above example... It should help a lot. I will leave it at that. Thanks again.
