### ISSUE TITLE
Serialization of UnmodifiableCollection

### ISSUE THREAD

**Issue by lachty** [RuedigerMoeller/fast-serialization#126]
Serialization of `UnmodifiableCollection` fails. 

Test case (version 2.45):

`FSTConfiguration FST_CONF = FSTConfiguration.createDefaultConfiguration();`
`Collection<BigDecimal> original = Collections.unmodifiableCollection(`
`           new ArrayList<>(Arrays.asList(new BigDecimal[] {BigDecimal.ONE})));`
`byte[] asByteArray = FST_CONF.asByteArray(original);`
`Collection<BigDecimal> clone = (Collection<BigDecimal>) FST_CONF.asObject(asByteArray);`

![sererr](https://cloud.githubusercontent.com/assets/19260805/15105587/2a3ad55a-15c3-11e6-9b4f-a17c002f92c5.PNG)

I tried to fix it with modification of `FSTUnmodifiableCollectionSerializer `class. I added 

`if (UNMODIFIABLE_COLLECTION_CLASS.isAssignableFrom(objectClass)) {`
`     Collection res = new ArrayList(len);`
`     fillArray(in, serializationInfo, referencee, streamPosition, res, len);`
`     return Collections.unmodifiableCollection(res);`
`}`

into the `instantiate(...)` method. This modification fixed the problem and serialization of `UnmodifiableCollection` is now being done correctly. 

I am not familiar with principles of FST, so I don´t want to make pull reguest so please consider if my modification is correct.

**Comment by RuedigerMoeller** [comment]
Hi thanks for the report and fix. FSTUnmodifiableCollectionSerializer is the right place to fix it, so you might do a pull request, however as its only a snippet of code I can also paste it.

**Comment by lachty** [comment]
I made pull request. It´s my first time using git a github, so hopefully i did it right :-)

**Comment by RuedigerMoeller** [comment]
Thanks a lot :)

**Comment by RuedigerMoeller** [comment]
the regression was introduced by a JSON codec related unmodifiable serializer which accidentally was added globally so side-effected binary serialization codec.

fixed with 2.46
