### ISSUE TITLE
writeReplace and FSTArrayListSerializer

### ISSUE THREAD

**Issue by rimmeraj** [RuedigerMoeller/fast-serialization#133]
I have a list of classes that implement writeReplace. Depending on the state of the object they either return a proxy or the actual materialized object.  In FSTArrayListSerializer.writeObject as you are looping through the objects you store FSTClazzInfo lastInfo. If the classes are the same then you use that for your serialization info. In my case the first item transforms from proxy to object so the class is the proxy and the return type is the materialized object. When it gets to the second item which is also a proxy since the classes are the same it uses the materialized class for the class info and thus the proxies wrtiteReplace method is not being called. The second and subsequent objects are not being written properly.  These proxies are cglib generated.

**Comment by RuedigerMoeller** [comment]
hm .. good catch, that's a really tricky corner case :). The clzinfo optimization speeds up arraylists containing objects of same class (also avoids writing a class tag afair). I'd try to find a well performing solution catching the writeObject use case or at least provide a slow but correct arraylist serializer which could be registered at fstconfiguration for cases similar to yours.

Can you provide a failing testcase ?

**Comment by RuedigerMoeller** [comment]
actually there is already logic catching the case. In case 'compatible mode' is detected (JDK serialization methods used), but it seems to miss your case (likely due to replaced Object)

```java
    public FSTClazzInfo writeObjectInternal(Object obj, FSTClazzInfo ci, Class... possibles) throws IOException {
        if ( curDepth == 0 ) {
            throw new RuntimeException("not intended to be called from external application. Use public writeObject instead");
        }
        FSTClazzInfo.FSTFieldInfo info = getCachedFI(possibles);
        curDepth++;
        FSTClazzInfo fstClazzInfo = writeObjectWithContext(info, obj, ci);
        curDepth--;
        if ( fstClazzInfo == null )
            return null;
        return fstClazzInfo.useCompatibleMode() ? null:fstClazzInfo;
    }
```

**Comment by RuedigerMoeller** [comment]
on a side note: writeReplace mechanism is kind of inelegant and slow as hell. You can do much more flexible Object replacing magic registering fst serializers. E.g. see https://github.com/RuedigerMoeller/kontraktor/blob/trunk/src/main/java/org/nustaq/kontraktor/remoting/encoding/CallbackRefSerializer.java for an example on how t completely replace and transform objects once they are passed out/in of a process.

**Comment by rimmeraj** [comment]
Not my choice.  Dealing with some legacy Hibernate proxies.

I have a test case. How do you want it. There are three files and the test file itself.

**Comment by rimmeraj** [comment]
Inline ...

public class BaseClass implements Serializable
{
	public String value;
	
	private Object writeReplace() throws ObjectStreamException
	{
		if(value.equals("morphMe"))
		{
			Morpher m = new Morpher();
			m.value="you have morphed";
			return m;
		}
		return this;
	}
}

public class Morpher extends BaseClass
{
}
public class Container implements Serializable
{
	public List<BaseClass> list = new ArrayList<>();
}


public void test_messedArray() 
		throws IOException, ClassNotFoundException
	{
		Container c = new Container();
		
		BaseClass b1 = new BaseClass();
		b1.value="morphMe";
		c.list.add(b1);
		BaseClass b2 = new BaseClass();
		b2.value="morphMe";
		c.list.add(b2);
		
		ByteArrayOutputStream buf = new ByteArrayOutputStream();
		ObjectOutput out = bean.toOutputStream(buf);
		out.writeObject(c);
		out.close();
		
		ObjectInput in = bean.fromInputStream(new ByteArrayInputStream(buf.toByteArray()));
		
		Container res = (Container) in.readObject();
		assertEquals("you have morphed",((Morpher)res.list.get(0)).value);
		assertEquals("you have morphed",((Morpher)res.list.get(1)).value);
	}

second assert fails because writeReplace was not called on the second BaseClass

bean.toOutputStream/fromInputStream; is simply a wrapper around 

config = FSTConfiguration.getDefaultConfiguration();
config.getObjectOutput(out)/onfig.getObjectInput(in);

**Comment by rimmeraj** [comment]
I have had a look over the code and it looks like the only reason you return the class info is for List/Map optimizations. Do we just not have to keep the original around and then if the value was replaced send the original value?  Shall I do a pull request and fix? Add a test?

**Comment by RuedigerMoeller** [comment]
would be welcome, quite busy currently :)

**Comment by rimmeraj** [comment]
I see you merged the pull request.  Any chance of a release?

**Comment by RuedigerMoeller** [comment]
Have to test and review first, but will release latest next weekend

**Comment by RuedigerMoeller** [comment]
the pull request submitted seems to fix things, however I am not sure if it produces side effects as previously in case of writeReplace the class info of the replced object was returned. Apparently this does not hurt, as all tests pass
