### ISSUE TITLE
Help: java.lang.RuntimeException: class not found CLASSNAME

### ISSUE THREAD

**Issue by gunjanthesystem** [RuedigerMoeller/fast-serialization#135]
First, thanks for your serialization framework.

It would be great if you can suggest something for my problem. I am getting the following runtime exception when deserialising using the below method:
"java.io.IOException: java.lang.RuntimeException: class not found CLASSNAME: loader:sun.misc.Launcher$AppClassLoader@73d16e93
	at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243)
	at org.activity.util.Serializer.fstDeSerializeThis(Serializer.java:161)"

Note that serialisation and deserialisation works fine if done in same execution, but gives the above error if done in separate execution. Kindly suggest,

My implementation is as follows:
```java
public static Object fstDeSerializeThis(String fileName)
	{
		Object obj = null;
		FileInputStream fis = null;
		FSTObjectInput in = null;``
		System.out.println("Deserialising ..." + fileName);
		long dt = System.currentTimeMillis();
		try
		{
			RandomAccessFile raf = new RandomAccessFile(fileName, "rw");
			fis = new FileInputStream(raf.getFD());
			in = new FSTObjectInput(fis);
			obj = in.readObject();
			in.close();
			raf.close();
			long lt = System.currentTimeMillis();
			System.out.println("Successfully fstdeserialised " + fileName + " in " + (lt - dt) / 1000 + " secs");
			
		}
		catch (Exception ex)
		{
			ex.printStackTrace();
		}
		return obj;
	}

public static void fstSerializeThis(Object obj, String fileName)
	{
		FileOutputStream fos = null;
		FSTObjectOutput out = null;
		long dt = System.currentTimeMillis();
		try
		{
			RandomAccessFile raf = new RandomAccessFile(fileName, "rw");
			fos = new FileOutputStream(raf.getFD());
			out = new FSTObjectOutput(fos);
			out.writeObject(obj);
			out.close();
			raf.close();
			long lt = System.currentTimeMillis();
			System.out.println("Successfully fstserialised " + fileName + " in " + (lt - dt) / 1000 + " secs");
		}
		
		catch (Exception ex)
		{
			ex.printStackTrace();
		}
		
	}
```

**Comment by rimmeraj** [comment]
Usually when you see an empty CLASSNAME it means the inputstream is empty. I would check the file size and contents on disk and see that is in there.

**Comment by linlihai** [comment]
mark..

use kafka message serialization.

**Comment by RuedigerMoeller** [comment]
Hi sorry, I don't have capacity and time to deal with beginners issues as this gets overboard (also receiving mails frequently).
