### ISSUE TITLE
EnumSet with anonymous enums serialization

### ISSUE THREAD

**Issue by john9x** [RuedigerMoeller/fast-serialization#139]
Hi!

Test code to reproduce:
```
class Test {
enum SomeEnum {
        plain, override {
            @Override
            public boolean getSomeBool() {
                return true;
            }
        };

        public boolean getSomeBool() {
            return false;
        }
    }

    static class Clazz implements Serializable {
        public Set<SomeEnum> enumSet = EnumSet.of(SomeEnum.override);

    }

    public static void main(String[] args) {
        FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();
        byte[] bytes = conf.asByteArray(new Clazz());
        Clazz o = (Clazz) conf.asObject(bytes);
        System.out.println(o);
    }
}
```

will fail with exception:
Caused by: java.lang.ClassCastException: class com.navixy.ResourcesTest$SomeEnum$1 not an enum
	at java.util.EnumSet.noneOf(EnumSet.java:110)
	at org.nustaq.serialization.serializers.FSTEnumSetSerializer.instantiate(FSTEnumSetSerializer.java:70)

If enumSet in given object to serialize/deserialize contains anonymous enum that ordinal less than any normal enum.

Method org.nustaq.serialization.serializers.FSTEnumSetSerializer#writeObject
writes classTag for first element in set - if it will be anonymous deserialization will fail.

**Comment by RuedigerMoeller** [comment]
fixed by pullrequest. Thanx :)
