### ISSUE TITLE
FSTConfiguration.asObject(byte[]) throws StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by MartinanderssonDotcom** [RuedigerMoeller/fast-serialization#141]
There's a statement in this method like so:

    System.out.println("unable to decode:" +new String(b,0,0,Math.max(b.length,100)) );

If this statement is reached, and `b.length < 100`, then this line will crash with a `StringIndexOutOfBoundsException`. Which also means that the original exception is lost.

**Comment by RuedigerMoeller** [comment]
agreed, will be fixed with next version

**Comment by RuedigerMoeller** [comment]
fixed by pull request
