### ISSUE TITLE
TreeMap support is not perfect

### ISSUE THREAD

**Issue by Lintel-X** [RuedigerMoeller/fast-serialization#144]
I got the **same** byte array with my workmate got from Redis. But somtimes I got the empty TreeMap object from FST like {}, and size() of it is **-19**, isEmpty() of it is **false** . When I changed to HashMap, it works perfectly.

**Comment by RuedigerMoeller** [comment]
Thanks for your report. Can you provide a reproducing testprogram, pls ? Just to ensure its not caused by racing conditions or IO issues of your application.

**Comment by RuedigerMoeller** [comment]
also platform running on + version would be a nice information :)

**Comment by Lintel-X** [comment]
@RuedigerMoeller I didn't use FST directly, I used a plugin from a MVC framework to get data from Redis, the source code of the directly invoked method is as below:
`public Object valueFromBytes(byte[] bytes) {
		if(bytes == null || bytes.length == 0)
			return null;
		
		FSTObjectInput fstInput = null;
		try {
			fstInput = new FSTObjectInput(new ByteArrayInputStream(bytes));
			return fstInput.readObject();
		}
		catch (Exception e) {
			throw new RuntimeException(e);
		}
		finally {
			if(fstInput != null)
				try {fstInput.close();} catch (IOException e) {LogKit.error(e.getMessage(), e);}
		}
	}`
I passed the same byte array with my workmate but got the different result randomly.
And my JDK version is 1.7.067，FST version is 2.47

**Comment by RuedigerMoeller** [comment]
problem might be if the treemap has a comparator set, if your local implementation of the comparator differs from your collegue you're in trouble. Another issue might be different versions of fst used.

I really need a reproducer, as I don't run into errors using your snippet above with a treemap.
What do you mean with randomly ? Same byte array, different results or same use case (but different byte arrays) ?

 
btw:
* you can decode a byte[] faster using FSTConfiguration.asObject(byte[]).

**Comment by Lintel-X** [comment]
@RuedigerMoeller "Randomly" means same byte array, different results, I simply used the redis plugin(from a famous Chinese MVC framework called JFinal<https://github.com/jfinal/jfinal> ) as below:
final Cache redisCache = Redis.use(CACHE_NAME);
redisCache.set(TEST_CACHE_NAME, obj);
...
redisCache.get(TEST_CACHE_NAME);

public <T> T get(Object key) {
		Jedis jedis = getJedis();
		try {
			return (T)valueFromBytes(jedis.get(keyToBytes(key)));
		}
		finally {close(jedis);}
	}

**Comment by RuedigerMoeller** [comment]
Hi,

actually I don't have time to get involved with the framework and stuff. 

I will investigate if you can provide me a breaking ready-to run testcase. I have spent a lot of time debugging 3rd party issues such as concurrent modification of data-in-serialization and so on.

Sorry, but at least I don't make any mony from open source, so its a community effort which means we need to share workload. And reproducing an issue is often a big part of solving an issue.

**Comment by RuedigerMoeller** [comment]
closed, no help from user
