### ISSUE TITLE
Question: May i switch from 1.x to 2.x without any problem

### ISSUE THREAD

**Issue by fgaule** [RuedigerMoeller/fast-serialization#145]
I have read the doc https://github.com/RuedigerMoeller/fast-serialization/wiki but it doesn't say anything about retrocompability between versions. May i serialize with 1.x and read with 2.x successfully?

Thanks!

**Comment by RuedigerMoeller** [comment]
there are only minor api changes. Note that it is not possible to read 1.x
serialized binaries using 2.x

2016-08-18 15:50 GMT+02:00 Federico Gaule <notifications@github.com>:
