### ISSUE TITLE
java.io.IOException: java.lang.RuntimeException: unable to find class for code 253

### ISSUE THREAD

**Issue by seanlees** [RuedigerMoeller/fast-serialization#156]
I got a problem when using fst. i can't Solve it..

my code is very simple: 

`public class SerializeUtil {
    private final transient static FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();

```
public static byte[] serialize(Object object) {
    if (object == null) {
        return null;
    }

    byte barray[] = conf.asByteArray(object);

    return barray;
}

public static Object unserialize(byte[] bytes) {
    if (bytes.length <= 0) {
        return null;
    }
    return conf.asObject(bytes);
}
```

}`

but call unserialize method ,sometimes it's error :

`Caused by: java.io.IOException: java.lang.RuntimeException: unable to find class for code 253
        at org.nustaq.serialization.FSTObjectInput.readObject(FSTObjectInput.java:243) ~[fst-2.45.jar:na]
        at org.nustaq.serialization.FSTConfiguration.asObject(FSTConfiguration.java:1122) ~[fst-2.45.jar:na]
        at xxx.xxx.v3.cache.redis.SerializeUtil.unserialize(SerializeUtil.java:54) ~[xx-redis-1.0.3-SNAPSHOT-v3.jar:na]`

I don't know why it's like this.   hope you can help me to analyze.

please help me , very thanks !

**Comment by RuedigerMoeller** [comment]
i need the object structure you  are serializing or a simple reproducing testcase. also some platform information would be useful (android?, jdk?)

**Comment by seanlees** [comment]
i use oracle jdk 1.7.0_79

**Comment by seanlees** [comment]
object structure :
`public class AccessTokenInfo implements Serializable {

    /**
     * a serializable javabean
     */
    private Client client;

    /*
     * a serializable javabean
     */
    private AuthInfo authInfo;

    private String openId;

    private String accessToken;

    /**
     *  a enum
     */
    private AccessTokenType accessTokenType;

    /**
     * a enum 
     */
    private Constants.GrantType grantType;

    /*private List<String> scopeList;*/

    private Long expireTime;

    private Long createTime;

    public enum AccessTokenType implements Serializable {
        user,
        client
    }

   getting method...
   setting method...
}

`

**Comment by seanlees** [comment]
He works well for most of the time, but sometime it get error ,so i have no get simple reproducing testcase

**Comment by RuedigerMoeller** [comment]
ensure you use the latest version of fst, and check for multithreading issues (mutation of objects during serialization) and corruption in the base stream. As quite some large production systems run using fst, I'd assume "occasional" failure to be likely located in the outside code.
Can you provide some more info about your failure scenario (multithreading etc.)

**Comment by RuedigerMoeller** [comment]
not enough ninformation

**Comment by asjayli** [comment]
Same problem: java.io.IOException: java.lang.RuntimeException: unable to find class for code 252
