### ISSUE TITLE
FST support lambda serialization?

### ISSUE THREAD

**Issue by andre-paris** [RuedigerMoeller/fast-serialization#161]
FST support lambda serialization?
If yes, can you provide an example?
Thanks

**Comment by RuedigerMoeller** [comment]
ofc it does support this same as jdk-serialization. as long the function interface is marked serializable.

e.g. 
```java 
public interface MyRunnable extends Runnable,Serializable {}

public Sample implements Serializable {
 MyRunnable toRun = () -> System.out.println("Hello");
}
```

note that the byte code of a lambda is not serialized, so the deserialization program needs exactly the same version of the class + lambda.

**Comment by andre-paris** [comment]
Thanks!
