### ISSUE TITLE
Some code still licensed under LGPL?

### ISSUE THREAD

**Issue by sgustafsson** [RuedigerMoeller/fast-serialization#171]
Referring to issues #92 and #41 : there's still some code  in folder /src/test and /src/test_nojunit which has references to the LGPL license which once governed this complete project. 
Is this test code still actually covered by LGPL, or are those comments forgotten leftovers from the time of license switch?

**Comment by RuedigerMoeller** [comment]
these are apparently leftovers. Anyway the test code is not part of the library artifact.

**Comment by sgustafsson** [comment]
thanks for the clarification
