### ISSUE TITLE
FSTBytezEncoder doubles the size of its output buffer

### ISSUE THREAD

**Issue by abyrd** [RuedigerMoeller/fast-serialization#176]
org.nustaq.serialization.coders.FSTBytezEncoder::ensureFree has autoResize functionality which is very useful when writing large object trees and the final size is unknown. The buffer size is generally doubled each time it runs out of space. This poses a problem when serializing really big objects: the buffer will grow from e.g. 550MB to 1.1GB to 2.2GB to 4.4GB. At these larger sizes we can start hitting architectural limits where allocations are refused, making all buffer sizes over a few hundred MB susceptible to allocation failures.

As a solution, I would suggest switchable autoResize behavior from exponential to linear growth, or growth that switches from exponential to linear beyond a certain size e.g. 500MB. I can provide an implementation in a pull request if this is of interest.

**Comment by abyrd** [comment]
Another solution could be to add a method BasicBytez::ensureCapacity(long minimumSize) that, if necessary, would expand the current instance of BasicBytez to be able to hold at least minimumSize bytes. The current system places this ensure-capacity logic in the caller and forces copy-based logic to expand the buffer, but it may make more sense to encapsulate the resizing logic within the BasicBytez implementation class, allowing buffers to be resized in place rather than making new objects, and leaving the exact resize strategy up to the implementation class.

Again, I could provide an implementation pull request if this is of interest.

**Comment by RuedigerMoeller** [comment]
sounds good, I am taking pull reuqests, however with rising use, fst starts basically open source means work@zero income, so it might take some time until i put this to a new public release. 
On the other hand you will hit integer array limit anyway when going above 1.5 GB ? A better solution IMO would be to have a memory mapped binary encoded offheap tree and only serialize data of a single tree node (similar to persistant hashmaps fst provides).

**Comment by RuedigerMoeller** [comment]
could you provide a pull request ? I am not sure it's a good idea to provide this at "Basicbytes" level as some implementations lack the ability to be resized. Maybe use a tagging interface instead ?

**Comment by RuedigerMoeller** [comment]
oops, I think this belongs to the FSTBytezEncoder not BasicBytez ..

**Comment by RuedigerMoeller** [comment]
You could achieve desired behaviour by setting a subclassed FSTStreamCoderFactory providing a subclass of FSTBytezEncoder.
