### ISSUE TITLE
 should not  use "System.out.println" in release version,please!

### ISSUE THREAD

**Issue by yuanhaoliang** [RuedigerMoeller/fast-serialization#186]
org.nustaq.serialization.FSTConfiguration#asObject

`

    /**
     * convenience
     */
    public Object asObject( byte b[] ) {
        try {
            return getObjectInput(b).readObject();
        } catch (Exception e) {
            System.out.println("unable to decode:" +new String(b,0,0,Math.min(b.length,100)) );
            try {
                String debug = new String(b, "UTF-8");
            } catch (UnsupportedEncodingException e1) {
                //
            }
            try {
                getObjectInput(b).readObject();
            } catch (Exception e1) {
                // debug hook
            }
            FSTUtil.<RuntimeException>rethrow(e);
        }
        return null;
    }
`

It should not use 'System.out.println' to output message to the console.

I suggest that to  use Log system or make a RuntimeException wrapper to contain the error message.

**Comment by RuedigerMoeller** [comment]
agreed ;)

**Comment by RuedigerMoeller** [comment]
fixed with 2.51 (contribution of cakofony)

**Comment by yuanhaoliang** [comment]
there is still the same in 2.52 version.

**Comment by RuedigerMoeller** [comment]
@yuanhaoliang could you provide a pull request resolving this **without adding a logging framework** using FSTLogger Api/Wrapper (part of fst) ?

**Comment by RuedigerMoeller** [comment]
has been fixed by @cakofony
