### ISSUE TITLE
FST doesn't throw InvalidClassException when serial version UID is changed

### ISSUE THREAD

**Issue by bkatwal** [RuedigerMoeller/fast-serialization#187]
Hi,

I am using FST to serialize and deserialize java objects in/out of redis.
FST version used: 1.63
Below is the code used:

static FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();

for serialize:
byte[] bytes = conf.asByteArray((Serializable) object);

Deserialize:
conf.asObject(uncompressedBytes);

Issue:
After I serialize and save in redis I am changing the class Serial version UID, but FST is still able to deserialize same class object. I want it to throw exception(InvalidClassException), as in plain java, so that I can invalidate that cache from redis. 

Let me know how can I achieve this with FST?

**Comment by RuedigerMoeller** [comment]
se #188
