### ISSUE TITLE
Error logging

### ISSUE THREAD

**Issue by cakofony** [RuedigerMoeller/fast-serialization#195]
It can be difficult to trace execution and debug issues without logging. Would you mind if I push a change adding a dependency on slf4j and some logging in error cases?

**Comment by RuedigerMoeller** [comment]
no more dependencies pls .. the android guys keep nagging me about that (issue with limited amount of methods on android or so).

maybe some lightweight (simple public static) wrapper could do it:

along the lines of
```java
    public interface Log {
        void msg(Thread t, int severity, Object source, Throwable ex, String msg);
    }
```

**Comment by RuedigerMoeller** [comment]
also slf4j means trouble for jdk9/jigsaw ..

**Comment by cakofony** [comment]
Good idea, I'll push something shortly!

**Comment by RuedigerMoeller** [comment]
great :)
