### ISSUE TITLE
Serialization of hibernate entities

### ISSUE THREAD

**Issue by lpinkowski** [RuedigerMoeller/fast-serialization#198]
Is it somehow possible to make fast-serialization not serialize lazy-loading hibernate object fields?

**Comment by RuedigerMoeller** [comment]
can you provide a demo testcase emulating the nature of lazy loading fields. Actually fst never calls any getters or methods on an object, so lazy loading can only be triggered by implementations of Externalizable or readObject/writeObject being implemented by the Hibernate objects.

**Comment by lpinkowski** [comment]
t seems that e
