### ISSUE TITLE
FSTSerializer : Deserialization error: java.lang.RuntimeException: read version tag -1 fieldInfo has 2

### ISSUE THREAD

**Issue by ritvik88** [RuedigerMoeller/fast-serialization#211]
Hi,

I have added one extra field in already serialized class and this class is used as a json response but when this class is deserialized below exception is returned

FSTSerializer            : Deserialization error: java.lang.RuntimeException: read version tag -1 fieldInfo has 2 
                                Deserialization error: java.lang.RuntimeException: read version tag 1 fieldInfo has 2 

Note: 1. FST serialized version that i am using is 2.40.
          2.  I tried @org.nustaq.serialization.annotations.Version(2) annotation, getting the above exception before using this annotation , getting below exception,

FSTSerializer            : Deserialization error: java.lang.RuntimeException: unable to find class for code 105

Please check above issue.

**Comment by RuedigerMoeller** [comment]
please provide a testcase + step by step instructions, also pls check with latest version, i cannot support for free like 50 releases backwards

**Comment by RuedigerMoeller** [comment]
closing - no response from submitter

**Comment by ritvik88** [comment]
Ok

**Comment by ritvik88** [comment]
Hi Ruediger,

How are you !!

I am getting the same issue again, while deserializing arraylist object. I am using FST 2.40 version.
Please see below testcase,

public class EntitySuperClass  implements Serializable{
private List<Entity> tags;
}

public class Entity  implements Serializable{
private String name;
private int id;
}

If i add new instance variable to **Entity** class(Forward compatibility), 

public class Entity  implements Serializable{
private String name;
private int id;
_// New instance variable_
private String address;
}

After deserialzing _EntitySuperClass_   object, I am getting below exception
_: class java.util.ArrayList deserialization problem_
java.io.IOException: java.lang.RuntimeException:

To handle this issue , i have added version check in super class like,

public class EntitySuperClass  implements Serializable{
@org.nustaq.serialization.annotations.Version(2)
private List<Entity> tags;

}


public class Entity  implements Serializable{

private String name;
private int id;
@org.nustaq.serialization.annotations.Version(2)
private String address

}


I am getting below exception

FSTSerializer : Deserialization error: java.lang.RuntimeException: read version tag -1 fieldInfo has 2
Deserialization error: java.lang.RuntimeException: read version tag 1 fieldInfo has 2


Please check, If u can help me out here.

Thanks
