### ISSUE TITLE
Deserialization of Non-Serializable object not working

### ISSUE THREAD

**Issue by Elgeor** [RuedigerMoeller/fast-serialization#22]
Hi, I have issue with your library. Unfortunately, I can not post here any source code to be more specific. It seems, when you deserialize my object which is not marked as Serializable, you read incorrect class name from stream which contains also data which are no more part of class name.

During my investigation I find out that in FSTStreamDecoder.readStringUTF() you are using readFInt() which returns incorrect value. In general, this can be also problem of serialization process, who knows. 
For more information please contact me at: stehlik.michal(at)gmail.com.

**Comment by nordfalk** [comment]
Hi, I need to serialize objects, that are not implementing Serializable interface.

Can you please state in cleartext whether this library supports (de)serialization of objects that are not implementing Serializable interface?

And, if yes, how to do it?

**Comment by debraj-manna** [comment]
> Hi, I need to serialize objects, that are not implementing Serializable interface.
> 
> Can you please state in cleartext whether this library supports (de)serialization of objects that are not implementing Serializable interface?
> 
> And, if yes, how to do it?

I also have the same query and was not sure where to ask this. So posted in [stackoverflow](https://stackoverflow.com/questions/71492552/does-fst-supports-deserialisation-of-objects-not-implementing-serializable-int)
