### ISSUE TITLE
能不能直接支持Netty的ByteBuf

### ISSUE THREAD

**Issue by hank-whu** [RuedigerMoeller/fast-serialization#222]
包装一层总是会有一些性能降低

**Comment by RuedigerMoeller** [comment]
?

**Comment by hank-whu** [comment]
can support netty ByteBuf directly？

**Comment by RuedigerMoeller** [comment]
* implement a custom serializer in order to serialize netty byte bufs.
* implement an FSTCoder on top of netty bytebuf (see examples: OnHeapCoder, OffHeapCoder, ..)

I won't add netty as a dependency
