### ISSUE TITLE
Slow serialization bug?

### ISSUE THREAD

**Issue by defunky** [RuedigerMoeller/fast-serialization#229]
Hi, I'm not sure if this is the correct place to put this. It might not even be related to your code but I'm kinda out of ideas. I'm developing a basic RPC server/client using FST, I've based the serializer of TCPObjectSocket shown in the wiki.

Here's the issue: I'm calling a method remotely from the client to server, however for some reason it's somewhat slow (250/500ms), however the for some reason I can cut down the speed to around approx 10ms. This is where the problem lies, for some reason returning an object from the server to client causes it to speed up to 10ms, while if I don't return anything (eg. void method) it slows down to (250/500ms)

Just to give you visual example (I can't really show my entire codebase), Client calls this method remotely, method gets executed:-

```
    public void remoteSetParam(String query, int index, Object obj) {
        try {
            PreparedStatement stm = pstms.get(query);
            paramSetters.get(obj.getClass()).accept(stm, index, obj);
            //serializer.writeObject(output, query); //Uncomment these two lines and it speeds up to 10ms
            //output.flush();
        } catch (Exception e) {
            e.printStackTrace();
        }
    } 
```

I know it's a long shot but I was hoping if you had any ideas what could be the causes of this. I'm using fst-2.52-onejar.jar as a dependency. 

Yourkit Hotspots on slow server:
![image](https://user-images.githubusercontent.com/17749501/33950615-c5f4541c-e024-11e7-8219-b8f2800d907f.png)

Yourkit Hotspots on fast server (Code is exactly the same with the only difference is what I specified above):
![image](https://user-images.githubusercontent.com/17749501/33950673-e9d7f438-e024-11e7-942c-70907ec6db48.png)

**Comment by RuedigerMoeller** [comment]
Maybe you are blocking the receiving thread ?. I have seen weird classes doing blocking IO during deserialization (e.g. reconnecting a database or checking an URL).

Also ensure your sockets are wrapped by a buffered IO stream / writer.

As fst is used for high performance remoting (see kontraktor) in several production systems its most probably an issue either in your app. Within 500 ms fst can serialize like 500MB of memory or so. You are doing something very wrong, however I don't have time to figure out issues in your app code. If you can boil it down to a repeatable test case, I'll will check it out though.
