### ISSUE TITLE
False impression on performance

### ISSUE THREAD

**Issue by bakmei** [RuedigerMoeller/fast-serialization#242]
Hi there,

I came across your tools and I decided to try it out and compare the performance versus the JDK one:

Here is what I got:

FST - Write - 91ms
FST - Read  - 98ms
JDK - Write - 12ms
JDK - Read  - 13ms

This is not what your tool claimed to be 10x faster, but it actually 8 times slower.  Here is my test code:

`
package com.dotdashline.tools.dataframe;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Random;

import org.junit.Assert;
import org.junit.Test;
import org.nustaq.serialization.FSTObjectInput;
import org.nustaq.serialization.FSTObjectOutput;

public class DoubleTest {

    @Test
    public void test() throws FileNotFoundException, IOException, ClassNotFoundException {
        DoubleHolder h = new DoubleHolder();
        double[] expected = createDoubleArray(260 * 20);
        h.set(expected);

        long start = System.currentTimeMillis();
        try (FileOutputStream fos = new FileOutputStream(new File("doublevalues.bin"));
                ObjectOutputStream oos = new ObjectOutputStream(fos)) {
            oos.writeObject(h);
        }

        System.out.println("JDK - Write - " + (System.currentTimeMillis() - start) + "ms");

        try (FileInputStream fis = new FileInputStream(new File("doublevalues.bin"));
                ObjectInputStream ois = new ObjectInputStream(fis)) {
            DoubleHolder actual = (DoubleHolder) ois.readObject();
            Assert.assertArrayEquals(expected, actual.get(), 0.000001);
        }

        System.out.println("JDK - Read  - " + (System.currentTimeMillis() - start) + "ms");
    }

    @Test
    public void testFST() throws FileNotFoundException, IOException, ClassNotFoundException {
        DoubleHolder h = new DoubleHolder();
        double[] expected = createDoubleArray(260 * 20);
        h.set(expected);

        long start = System.currentTimeMillis();
        try (FileOutputStream fos = new FileOutputStream(new File("doublevalues.fst"));
                FSTObjectOutput oos = new FSTObjectOutput(fos)) {
            oos.writeObject(h);
        }

        System.out.println("FST - Write - " + (System.currentTimeMillis() - start) + "ms");

        try (FileInputStream fis = new FileInputStream(new File("doublevalues.fst"));
                FSTObjectInput ois = new FSTObjectInput(fis)) {
            DoubleHolder actual = (DoubleHolder) ois.readObject();
            Assert.assertArrayEquals(expected, actual.get(), 0.000001);
        }

        System.out.println("FST - Read  - " + (System.currentTimeMillis() - start) + "ms");
    }

    private double[] createDoubleArray(int len) {
        Random r = new Random(System.currentTimeMillis());
        double[] ret = new double[len];
        for (int i = 0; i < ret.length; i++) {
            ret[i] = r.nextDouble();
        }
        return ret;
    }
}
`

**Comment by RuedigerMoeller** [comment]
sorry, you probably suffer from a lack of understanding on many things

* warm up the jit properly
* serialization is not about writing double values to a a stream. You are not measuring serialization but the performance of java streams and the intrinsic writeDoubleArray.
* you are creating (internally) a new FSTConfiguration with each call
* as the vm uses intrinsic calls, writing double arrays can be slightly faster. This does not apply to real world use cases.
* pls read before writing ;)
* also consider ~1000 starring people and ~20k mvn downloads from ~16k distinct IP's are most probably not retards having fallen by a big scam.

here are a lot of properly crafted benchmarks https://github.com/RuedigerMoeller/serialization-benchmark

here is a result with many libs (https://github.com/RuedigerMoeller/fast-serialization/wiki/Benchmark)

**Comment by bakmei** [comment]
Sorry if I did offend you.  I do have a real use case for my project which I need to serialize many double arrays to files for caching purpose.  That's why I was seeking a quick way to do it and came across your tools.  It's ok that you don't admit it is a real world use case.  What I observed here is that, one doesn't fit all, according to your comments.
