### ISSUE TITLE
createDaultConfiguration and the serialise a String returns -4 10 <string bytes>

### ISSUE THREAD

**Issue by woodmawa** [RuedigerMoeller/fast-serialization#257]
doing a simple serialisation test like this 
`import org.nustaq.serialization.FSTConfiguration

FSTConfiguration ser = FSTConfiguration.createDefaultConfiguration()

byte[] bytes = ser.asByteArray("Hello");
System.out.println(new String(bytes,"UTF-8"))

Object deser = ser.asObject(bytes)
println "deserialised object shows as $deser"`

when i do that the asByteArray method returns -4 and 10 as first two bytes.  Wasnt expecting that 

is this me doing something wrong or does the two extra bytes mean something 

works fine with json fst and wraps the string with "" - no strange bytes on that

**Comment by RuedigerMoeller** [comment]
your expectations are wrong. there is some additional data inside a serialized byte[] e.g. to compress package names and avoid serializing class names twice etc.
