### ISSUE TITLE
Same Object has different bytes 

### ISSUE THREAD

**Issue by daigaigai520** [RuedigerMoeller/fast-serialization#277]
my code likes this:
![image](https://user-images.githubusercontent.com/12746046/53296353-b3643380-3848-11e9-9487-de3726ff8d08.png)

and use it this, which runs on android platform.
![image](https://user-images.githubusercontent.com/12746046/53296372-eefefd80-3848-11e9-875f-6a31b9e1a5a1.png)

but has different result: 
![image](https://user-images.githubusercontent.com/12746046/53296397-2ff71200-3849-11e9-8fff-dcd0ecc02519.png)
before `14:48:59.885`, it always `0, 15, 2, -4`. it is error ,and  I can't deserialize on other project.
but after that it is `0, 15, 1 -4`.it changes to right, so I cant deserialize now.

I do not know what happen at 14:48:59.And I don't know how to fix it

my version : 
```
   <dependency>
                <groupId>de.ruedigermoeller</groupId>
                <artifactId>fst</artifactId>
                <version>2.57</version>
  </dependency>
```

**Comment by Arglanir** [comment]
According to FSTMapSerializer, this "2" or "1" is the size of the map that had to be serialized.
This number is exactly the one returned by the size() method of the map.
Then FSTMapSerializer iterates over the map using an iterator, writing each key then value (-4 to tell it's a String)
Would it be possible that another thread modifies this map between the call to size() and the call to iterator() (not shown in your code) (if it was modified during iteration it would probably throw a ConcurrentModificationException...) ?

**Comment by daigaigai520** [comment]
thanks very much .@Arglanir 
i will check this by add some log to print the map's value.
