### ISSUE TITLE
Question about *NoShared classes

### ISSUE THREAD

**Issue by jschewebbn** [RuedigerMoeller/fast-serialization#298]
I'm doing message passing in my application, so from reading the documentation for `FSTObjectOutputNoShared` it seems that this is the class to be using. I see that read/writeObject is not supported, which should be OK. What happens with objects referenced multiple times? Do they just get written multiple times? 

Will a cycle cause a crash?

Are there other downsides to using this class?

I did a test for size and using FSTObjectOutput my messages serialized to 11,002,572 bytes. Using the no shared class the size is 3,736 bytes. Is this expected?

**Comment by RuedigerMoeller** [comment]
in noshared mode, no object reuse is supported, so cyclic references will crash. It is a special option to squeeze out some nanoseconds with plain message-like objects. I don't recommend it as it easily can lead to unexpected errors. for some use cases "noShared" is even slower. For plain objects it gives an advantage of 10-15% at best
