### ISSUE TITLE
java.io.File serializer

### ISSUE THREAD

**Issue by Show-HanHan** [RuedigerMoeller/fast-serialization#317]
When I use the FST, I encounter a problem. The problem description is "cannot support legacy JDK serialization methods in crossplatform mode. Define a serializer for this class java.io.File". How do I define a file serializer? Tks.

**Comment by javawxx** [comment]
define a serializer extend org.nustaq.serialization.FSTBasicObjectSerializer , then add into org.nustaq.serialization.FSTSerializerRegistry

**Comment by Show-HanHan** [comment]
> define a serializer extend org.nustaq.serialization.FSTBasicObjectSerializer , then add into org.nustaq.serialization.FSTSerializerRegistry

OK, I'll try. Thank you
