### ISSUE TITLE
Externalizable behavior is different from the JDK implementation for multiple instances

### ISSUE THREAD

**Issue by lalmeras** [RuedigerMoeller/fast-serialization#38]
Hi,

I work with Guillaume Smet who reported #36 . The proposed fix works fine for test case we submitted, but after further investigation, we notice that behavior is incorrect when a same Externalizable / readResolve instance is serialized several times (in different fields, or twice in a collection for example).

In this case, only the first deserialized instance is correct (both external and readResolve contract are handled). For subsequent instances, readResolve is not called and raw instance is used.

As multiple instances are serialized only once, then are serialized as reference, I suppose this bug is caused by an incorrect reference caching during deserialization (raw instance is cached during first deserialization, then this raw instance is reused without calling readResolve), but I do not dig further.

You can find here  a simple test case : http://share.openwide.fr/share/zone/lalmeras/2196471291
There is 3 test cases which serialize twice the same instance :
 * as two fields of a same bean
 * as two elements of a list
 * as a field and an element of a set

They all fails (fst v2.12).

Thanks

**Comment by lalmeras** [comment]
We no longer encounter this issue (tested version : 2.18)

**Comment by RuedigerMoeller** [comment]
closed, will not provide backports for 1.x anymore
