### ISSUE TITLE
Problem when serializing an object with two stack fields

### ISSUE THREAD

**Issue by pabloperezromani** [RuedigerMoeller/fast-serialization#39]
Hi, I got a NullPointerException when I tried to serialize an object from a custom class which has two stack of string fields, but there wasn't any problem when serializing objects with only one of that field (so I suppose it's not only a matter of Stack class incompatibility). Both cases can be tested through the following code:

    import java.io.IOException;
    import java.io.Serializable;
    import java.util.Stack;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    import org.nustaq.serialization.FSTConfiguration;
    import org.nustaq.serialization.FSTObjectInput;
    import org.nustaq.serialization.FSTObjectOutput;

    public class FSTEqualFieldsTest {

    static class OneStackClass implements Serializable {

        Stack<String> a;

        public OneStackClass(Stack<String> a) {
            this.a = a;
        }
    }

    static class TwoStackClass implements Serializable {

        Stack<String> a;
        Stack<String> b;

        public TwoStackClass(Stack<String> a, Stack<String> b) {
            this.a = a;
            this.b = b;
        }
    }

    public static void main(String args[]) {

        OneStackClass osc = new OneStackClass(new Stack<String>());
        byte[] mywriteMethod1 = FSTSerialization.mywriteMethod(osc);
        OneStackClass myreadMethod1 = FSTSerialization.myreadMethod(mywriteMethod1, OneStackClass.class);
        System.out.println("object well serializated: " + myreadMethod1);
        //
        TwoStackClass tsc = new TwoStackClass(new Stack<String>(), new Stack<String>());
        byte[] mywriteMethod2 = FSTSerialization.mywriteMethod(tsc);
        TwoStackClass myreadMethod2 = FSTSerialization.myreadMethod(mywriteMethod2, TwoStackClass.class);
        System.out.println("object well serializated? " + myreadMethod2);

    }

    static public class FSTSerialization {

        final static FSTConfiguration configuration;

        public static FSTConfiguration getConfiguration() {
            return configuration;
        }

        static {
            configuration = FSTConfiguration.createDefaultConfiguration();
            configuration.setShareReferences(true);
            configuration.registerClass(
                    Stack.class,
                    String.class
            );
        }

        public static <T> T myreadMethod(byte[] stream, Class<T> c) {
            FSTObjectInput in = configuration.getObjectInput(stream);
            T result = null;
            try {
                result = (T) in.readObject(c);
            } catch (Exception ex) {
                Logger.getLogger(FSTSerialization.class.getName()).log(Level.SEVERE, null, ex);
            }
            return result;
        }

        @SuppressWarnings("null")
        public static byte[] mywriteMethod(Object toWrite) {
            return mywriteMethod(null, toWrite);
        }

        public static byte[] mywriteMethod(byte[] stream, Object toWrite) {
            FSTObjectOutput out = configuration.getObjectOutput(stream);
            try {
                out.writeObject(toWrite, toWrite.getClass());
            } catch (IOException ex) {
                Logger.getLogger(FSTSerialization.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                out.flush();
            } catch (IOException ex) {
                Logger.getLogger(FSTSerialization.class.getName()).log(Level.SEVERE, null, ex);
            }
            return out.getBuffer();
        }

    }

    }

**Comment by RuedigerMoeller** [comment]
closed, will not provide backports for 1.x anymore
