### ISSUE TITLE
Can it deserialize a stream created using JDKs built in serialization?

### ISSUE THREAD

**Issue by chrisco484** [RuedigerMoeller/fast-serialization#49]
I have a scenario where I have existing Java serialized streams stored in databases (BLOB fields) and files and these were serialized with the JDK's built in serialization from many years ago.

Can fast-serialization read in these old streams and realize that they are the original JDK and so deserialize using the JDKs deserializer instead of it's own?

**Comment by RuedigerMoeller** [comment]
No. the binary wire format is completely different. Only thing you can do to enable mixed use is to put a  tagging byte determining the serializer to use in the first place of a stream, though this also might have problems as JDK objectoutput afaik already writes stuff even if you just create it.

**Comment by chrisco484** [comment]
I understand, yes. The JDK native serialization format is verbose so it
doesn't surprise me that stuff is written even before you've streamed
the first object.

 

It would have been nice if the first int written to any JDK stream (or
any other serialization technology) was a "unique" magic number - the
sort of thing we used to do with object streams back in the C++ days
then we could read the first int to determine what kind of stream it
was.

 

Regards,

Chris

 

 

 

________________________________

**Comment by RuedigerMoeller** [comment]
[kept open as 'FAQ']
I think they actually do something like this, however there is more than a single byte. Bad if you are doing > million per second messaging as as a 15 byte tiny object is blown up in size > two times.
regards, 
Ruediger
