### ISSUE TITLE
Using Compression requires a ByteArrayOutputStream

### ISSUE THREAD

**Issue by ybisk** [RuedigerMoeller/fast-serialization#50]
Correct me if I'm wrong but one must use a ByteArrayOutputStream if using compression?

e.g.

``` java
      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      BufferedOutputStream buffered = new BufferedOutputStream(new GZIPOutputStream(bos));
      FSTObjectOutput oos = conf.getObjectOutput(buffered);
      oos.writeObject(chart);
      oos.flush();
      buffered.close();
      serialized_data.add(bos.toByteArray());
```

I only ask because of your comment to use `conf.asByteArray`

``` java
 byte barray[] = conf.asByteArray(mySerializableObject);
```

Which is simpler, cleaner, and more efficient(?) but at least for my data even with registering all the classes ~3x larger than after gzip.

Thanks!

**Comment by RuedigerMoeller** [comment]
Well, in the first place ensure bandwidth is your bottleneck. Zipping is rather expensive. If you are using kind of a webservice consider using a compressing reverse proxy like nginx, this will be more efficient. For LAN's compression almost never does pay off. This might even hold true for Smartphones with modern connectivity (test it).

conf.asByteArray isn't even the fastest possible way as it still creates and copies a byte array, however its the most safe and simplest way + takes care of reusing some stuff.

If you absolutely need compression done from your JVM (e.g. mobile clients), you'll have to create a ByteArrayOutputStream. However as compression is expensive, i think you can also create a new ByteArrayOutput from the byte array resulting from 'asByteArray'.

Performance hint: as the internal byte[] of ByteArrayOutputStream is protected, you can subclass ByteArrayOutputStream, granting access to buf[]+pos, as ByteArrayOutputStream.toByteArray will create another (unnecessary) copy of the bytes[]. 

Another option would be to look for more effective compression libs, which can operate directly onto byte[]. The optimal compression/speed trade off can only be decided on a per use case base.
