### ISSUE TITLE
Remote object serialization supported?

### ISSUE THREAD

**Issue by timolbg** [RuedigerMoeller/fast-serialization#59]
I am interested in using your library for replacing Java serialization, but I need support for replacing exported remote objects with stubs (Similar to MarshalOutputStream)?
Or is it possible to add this through some extension point?

**Comment by RuedigerMoeller** [comment]
Yes. I do this myself in kontraktor's actor remoting implementation.
Easiest way is to register custom object serializers for classes you want to generate stubs of. A custom serializer takes precedence over all other serialization related mechanics (such as externalizable, writeObject ..). Custom serializers allow to customize reading, writing + instantiation of serialized obejcts, e.g. for 'kontraktor' a reference to a local actor is replaced by writing+registering an ID for the actor ref. On read side, a forwarding proxy is silently instantiated.
In case you have no dedicated superclass for 'remoteable' classes, things might be slightly trickier, however it should not be too hard to tweak fst for that (e.g. see objectWillBeWritten method). Note you can easily loose a lot of performance if you add expensive checks for every object written.
