### ISSUE TITLE
Inclusion of a sample class which serves as an end to end example (Serialization and Deserialization with best practices for a multi threaded usage scenario) in the Documentation.

### ISSUE THREAD

**Issue by adiworkoholic** [RuedigerMoeller/fast-serialization#60]

**Comment by RuedigerMoeller** [comment]
is this sufficient ?
https://github.com/RuedigerMoeller/fast-serialization/tree/master/src/main/java/org/nustaq/net

the read/write locks are required only in case an application writes to the same objectsocket from different threads. FSTConfiguration is shared.

**Comment by adiworkoholic** [comment]
Thanks @RuedigerMoeller. It suffices.
