### ISSUE TITLE
Serialization of deeply nested structures

### ISSUE THREAD

**Issue by ybisk** [RuedigerMoeller/fast-serialization#65]
I stopped updating my mvn pulls at 2.16 because 2.17 causes my code to break but I hadn't had a chance to look through all of the commits until now.  I think the maximum recursion might be the problem because my code seems to work just fine if I limit the depth of my data-structures.  

https://github.com/RuedigerMoeller/fast-serialization/commit/040ebf999101fb173a2801ab71b60978f66f43a3

I limited the depth to test this theory but it's not actually a viable solution because I need depths of at least 150 in general.  I might be misattributing the error but I'm not sure how best to debug this.  Do you have any thoughts on how I might figure out what I can change in my code to be compatible? 

Thanks!

**Comment by RuedigerMoeller** [comment]
2.17 was a broken build. The changes you made to FSTIdentityMap do not make a difference, they just modify the probability/mechanics how hash collisions are managed.
checkout issue #57 which is related to your problem. Just upgrading to 2.27 should solve your problem.

**Comment by ybisk** [comment]
You're right, sorry, I placed the blame in the wrong place.  Unfortunately, 2.27 hasn't fixed my problem either though. 

I am serializing and traversing graph structures and it seems like I'm missing a reference in my deserialized graph structures so I'm missing a link when traversing them.   It's unclear which graphs run into this problem and which don't.  This wasn't showing up in 2.16 but it's possible I'm doing something very dumb. 

I'll try to spend the rest of the day on it and see if I can find what's what.  Thanks

**Comment by RuedigerMoeller** [comment]
Thanks for helping. What kind of exception error sympthom do you get ?

**Comment by ybisk** [comment]
Unfortunately the code is a bit hard to debug because of how complex the graph is.  I have three procedure calls on the deserialized graph.  1 & 2 compute probabilities, 3 aggregates.  3 crashes because 2 didn't touch every node (with 2.27) so there are nodes with 0 probabilities.  

I've written code that prints out every node that's touched by 2 so I can compare when I run with 2.16 and with 2.27.  If I choose a node that fails in 2.27 and write a conditional statement to track the node through stage 2 to understand why the node isn't touched,... the code begins to work.  If I comment out the if-statement and println,.. the code breaks again.

Because of this non-determinism it is proving very difficult to track down.  I'll be moving my code from bitbucket to an open-source release within the next 2months which I can link you to when it's ready [my unit tests fail with 2.27 but pass with 2.16] but I doubt that would prove fun.

I'll hope for a debugging epiphany.  Thanks

**Comment by RuedigerMoeller** [comment]
Any snippet reproducing the issue is welcome .. will keep this open.

"my unit tests fail with 2.27 but pass with 2.16" - hope it's not a side effect of bug fixing

**Comment by ybisk** [comment]
Sorry, I've been at a workshop for the past few days so I haven't been able to work on this.  I haven't had a chance to rewrite my code to test this theory but after talking to a few other people they claim they've had similar situations where Java8 has broken their unit tests.  I think specifically in the case of iterating over Collections.

**Comment by RuedigerMoeller** [comment]
no problem, don't stress yourself. If I can anyhow reproduce the issue I can investigate, else I'll keep this one luring np :-)

**Comment by RuedigerMoeller** [comment]
closed for now as missing input
