### ISSUE TITLE
FSTConfiguration.register(int, Class<?>) method needed

### ISSUE THREAD

**Issue by buko** [RuedigerMoeller/fast-serialization#68]
In a large application using dependency injection it's virtually impossible to guarantee that a set of classes will be registered in exactly the same order in all applications. If the purpose of the register method is just to provide an integer mapping and avoid class name serialization, might it be possible to offer a register(int, Class<?>) method that allows user-specified ints to be set.

(BTW, FST rocks. Seriously good work here.)

**Comment by RuedigerMoeller** [comment]
This is already possible (see end of post)

Hm .. that's pretty dangerous regarding id clash. Given registering is just a performance optimization, I'd recommend to just statically preregister most used classes.

e.g. (from a customer's app)
```java
String[] toRegister = new String[] {
                [....]
                "de.exchange.liveresults.face.datatype.XXX1",
                "de.exchange.liveresults.face.datatype.XXX2",
                "de.exchange.liveresults.face.datatype.XXX3",
        };
        for (int i = 0; i < toRegister.length; i++) {
            try {
                Class aClass = Class.forName(toRegister[i]);
                conf.registerClass(aClass);
            } catch (ClassNotFoundException e) {
                CGLogger.warning("could not register "+toRegister[i]);
                conf.registerClass(new Object() {}.getClass() ); // at least register a dummy
                // expected
            }
        }
```
however if you absolutely want to directly register classes (note: use id values from 5..65000) you can do
```java
conf.getClassRegistry().registerClass( class, id );
```

**Comment by RuedigerMoeller** [comment]
make it a public question
