### ISSUE TITLE
Registering enum instances during read

### ISSUE THREAD

**Issue by esemsch** [RuedigerMoeller/fast-serialization#77]
Hi,

I saw a lot of (identical) enum instances in the org.nustaq.serialization.FSTObjectRegistry#idToObject map during reading.  And then I noticed the comment on this line: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectInput.java#L474  After a brief inspection of FSTObjectOutput, I don't see any attempt at reusing the enum instances in the code.  It looks like they are always written with the tag ENUM and never as a HANDLE. So is there any other reason to store them in the idToObject map?

Thank you,

Eduard

**Comment by RuedigerMoeller** [comment]
Hm .. seems like the comment is right :). With growing user base I have become very careful in modifying things as in conjuction with JDK-ser emulation ("compatible mode") there are really obscure edge cases to break ..

**Comment by RuedigerMoeller** [comment]
..Addition: Note at read time registering id is not a hash put but an array store for most cases. In addition the array is accessed linear such that cache prefetch can be assummed (=> very little cost)

**Comment by esemsch** [comment]
My use case is a bit different as the input stream is .5 GB and the reuseMap in FSTObjectRegistry runs out of space quickly, so I get quite a lot of hash puts/lookups.

A minor one, but this line should probably return: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/main/java/org/nustaq/serialization/FSTObjectRegistry.java#L86  As it stands this is doing the lookup twice.

**Comment by RuedigerMoeller** [comment]
oops, nice find. Thanks a lot :). I consider removing the put for enums, however need have a close look before .. it's also that json/minbin codec might work different and ignore the ENUM tag and treat them as regular objects.

**Comment by esemsch** [comment]
Many thanks!  Looking forward to the next release.

**Comment by esemsch** [comment]
By the way.  I have just upgraded from 2.33 to 2.35 and the deserialization is 40% faster!!  It was about 20 seconds and is under 12 seconds now.  Brilliant, that's absolutely great stuff, thanks a lot!

**Comment by RuedigerMoeller** [comment]
Thanks, however the credits belong to yourself for spotting this. You seem to have  a lot of enums in your structures ..
