### ISSUE TITLE
missing standalone ZIP for version 2.37

### ISSUE THREAD

**Issue by luksch** [RuedigerMoeller/fast-serialization#82]
Any chance of getting your wonderful FST library version 2.37 as stand alone, much like the older versions? (Like https://github.com/RuedigerMoeller/fast-serialization/releases/download/v2.36/fst-2.36.zip )

**Comment by RuedigerMoeller** [comment]
have been lazy, but will add it to the release this weekend :)

**Comment by RuedigerMoeller** [comment]
btw, entering issues without giving a star is kind of bad style ;)

**Comment by luksch** [comment]
Sorry, fixed the latter issue :)

**Comment by RuedigerMoeller** [comment]
fixed the latter issue ;)
