### ISSUE TITLE
Suggestion: use different maven artifact id for 2.* versions

### ISSUE THREAD

**Issue by leons727** [RuedigerMoeller/fast-serialization#86]
I have a requirement to support both fst 1.63 and 2.39. Since package names changed in version 2, it should work, however the fact that both artifacts share same groupId/artifactId makes it tricky to take dependency on both of them using Maven. 

Of course it's possible to maintain one of the artifacts with a different artifactId in a local repository, but I wonder if it'd work better for others as well if v2 had artifactId `fst2`:

``` xml
<dependency>
    <groupId>de.ruedigermoeller</groupId>
    <artifactId>fst2</artifactId>
    <version>2.39</version>
</dependency>
```

**Comment by RuedigerMoeller** [comment]
Agree, will rename the artifact of fst 1. Unfortunately sonatype currently has issues (did not promote 2.40 artifacts for 3 days now ..)

**Comment by leons727** [comment]
Any updates on this? 2.40 is in http://central.maven.org/maven2/de/ruedigermoeller/fst, but there is no fst1...

**Comment by RuedigerMoeller** [comment]
erm .. no. haven't had a release of fst since .. maybe tomorrow :)

**Comment by RuedigerMoeller** [comment]
uploaded fst1 artifact to maven.org, should be visible within 1-3 days. Thanx for reporting + insisting ;)

**Comment by RuedigerMoeller** [comment]
something went wrong ..

**Comment by samhendley** [comment]
It would still be helpful to re publish the 1.63 artifact with a different artifact name. fst163 or something like that. Since they have the same artificatId and groupName maven will only let us have one on the path without some serious trickery.

**Comment by RuedigerMoeller** [comment]
i tried but it somehow did not work .. however 1.x is not supported anymore (have to save time to be able to support the major use cases of fst/kontraktor)
