### ISSUE TITLE
Serializtion issue when tomcat reload

### ISSUE THREAD

**Issue by hutch13015** [RuedigerMoeller/fast-serialization#87]
Hello,

Firstable, thanks for your work. I'm using redis for hibernate cache and I set the class Loader like you say in another issue.

FstRedisSerializer.getConf().setClassLoader(Thread.currentThread().getContextClassLoader());

But the problem is when the application reload, I have this exception:

n.s.s.exception.DefaultExceptionHandler: Unhandled exception caught by the Stripes default exception handler.
org.hibernate.PropertyAccessException: could not set a field value by reflection setter of myPackage....enum

This problem is only for deserialization enumeration

I use redis 1.6.2 and fst 2.40

Thank you.

**Comment by RuedigerMoeller** [comment]
FST caches a lot of stuff. You might need to create a new fst configuration object on reload and also clean up some thread locals / caches. 
In addition 

-FSTClazzInfo.sharedFieldSets 
-FSTDefaultClassInstantiator.constructorMap

must be cleared upon class/servlet reload.
once this is implemented you might need further debugging in order to find field/class references refering to old classes.

**Comment by hutch13015** [comment]
Thx for your reply,

I can see  the enum which crashes in classRegistry of the FST configuration but I do not know how I can reload it.
I use FST from redis-hibernate-cache which create a default configuration inside static final object, so i can't create it myself.

**Comment by RuedigerMoeller** [comment]
I am not tracking use of fst from other libs, which library includes fst ? I probably need to reproduce the scenario (quite time consuming ..) and might need to contact the library providers directly.
The crash comes from fst having cached a previous version of the enum class.

A simple solution could be to put serialized classes + fst into the common classpath of tomcat, so they are not redefined once you reload your app in tomcat.

**Comment by hutch13015** [comment]
I use this library https://github.com/debop/hibernate-redis
I already put jars in the common classpath of tomcat but i can't move my hibernate entities to tomcat. 

I think the problem come from the way debop initializes fst.
Inside FstRedisSerializer:
private static final  FSTConfiguration conf = FSTConfiguration.createDefaultConfiguration();

 I will add a request to his project.

**Comment by RuedigerMoeller** [comment]
pls give me issue url, so i can work this out with them

2015-09-15 16:04 GMT+02:00 hutch13015 <notifications@github.com>:

**Comment by hutch13015** [comment]
https://github.com/debop/hibernate-redis/issues/42

Thank you

**Comment by RuedigerMoeller** [comment]
Thank you, too :)

**Comment by RuedigerMoeller** [comment]
don't forget to stare ;)
