### ISSUE TITLE
Deserialization of serialized object not working

### ISSUE THREAD

**Issue by Elgeor** [RuedigerMoeller/fast-serialization#89]
Hi, 

I have strange error. I have object, which after serialization can not be deserialized. My object looks like this:
```java
public class JettyInfo {
	private final InetAddress ipAddress;
	private final Integer port;
	private final boolean isCoordinator;
	private final String controllerId;

	public JettyInfo(final InetAddress ipAddress, final Integer port, final boolean isCoordinator, final String controllerId) {
		this.ipAddress = ipAddress;
		this.port = port;
		this.isCoordinator = isCoordinator;
		this.controllerId = controllerId;
	}
	
	//getters for all fields
}
```

(De)Serializer is created like this:
```java
FSTConfiguration conf = FSTConfiguration.createFastBinaryConfiguration().setForceSerializable(true);
``` 
used like this: 
```java
conf.asObject(dataToDeserialize);
```

and result of serialization is following byte array: [-9, -111, 31, 0, 0, -4, 36, 0, 0, 0, 55, 0, 99, 0, 100, 0, 98, 0, 102, 0, 51, 0, 50, 0, 49, 0, 45, 0, 52, 0, 48, 0, 97, 0, 52, 0, 45, 0, 52, 0, 50, 0, 52, 0, 54, 0, 45, 0, 56, 0, 101, 0, 57, 0, 98, 0, 45, 0, 101, 0, 100, 0, 99, 0, 97, 0, 99, 0, 54, 0, 48, 0, 56, 0, 55, 0, 48, 0, 51, 0, 54, 0, 0]
I call deserialize, but instead of JettyInfo object I got exception:
```java
SerializationException: java.lang.ClassCastException: Cannot cast java.lang.Integer to JettyInfo 
```
what is really strange. This means, that following byteArray contains only integer value what is not true at all. I expect it will be JettyInfo and not Integer. What is even stranger is, same code is also used for different entities without any error. 
Btw. version of fst I tried are: 2.18 and 2.40 with same result.

**Comment by Elgeor** [comment]
It seems, serializing of InetAddress can cause this problem.

**Comment by RuedigerMoeller** [comment]
Hi, thanks for the report. I had issues with InetAddress in the past, however this should be fixed. I'll track down the problem as soon I have time.

In advance:
* try to use the default configuration as fastbinary is less tested and also makes heavy use of unsafe. It should be used only for well tested systems and if it actually is proven to make a difference for your application.
* you might want to register a custom serializer for the problematic class as it might take some days until i find time to fix the issue
* Cheers

**Comment by Elgeor** [comment]
Hi, thanks for quick response. This issue also occurred with defaultConfiguration. And you are right, custom serializer will solve this issue for sure. :)

**Comment by RuedigerMoeller** [comment]
ForceSerializable is a very special option, you should not rely on it regulary. Usually InetAddress is serialized by custom JDK mechanics, which are emulated by FST. However if you turn on "forceSerializable" things might go wrong / custom JDK code won't be executed properly. 

For me your testcodee worked, so it seems the failure is data dependent, so I'd need the actual data which makes this fail. See my sample class which works fine: https://github.com/RuedigerMoeller/fast-serialization/blob/master/src/test/ser/ForceSerIssue89.java

**Comment by RuedigerMoeller** [comment]
Maybe a better solution to "ForceSerializable" would be a by class override of serializability, so it would be less global and one could select a particular class only to behave different ..

**Comment by RuedigerMoeller** [comment]
forceserializable is a quirks/workaround option, one cannot expect this to transparently work for random classes (there is a reason JDK requires "Serializable" to be declared).
