### ISSUE TITLE
The pom file implies that the license is still LGPL

### ISSUE THREAD

**Issue by joey** [RuedigerMoeller/fast-serialization#92]
In the [pom.xml file lines 18-24](https://github.com/RuedigerMoeller/fast-serialization/blob/master/pom.xml#L18-L24), it says that the license is LGPL. The [README.md](https://github.com/RuedigerMoeller/fast-serialization/blob/master/README.md) file indicates that the license changed to ASL 2.0 in version 2.17 and the [LICENSE.md](https://github.com/RuedigerMoeller/fast-serialization/blob/master/LICENSE.md) file also indicates that the license is ASL 2.0.

Assuming the readme and license are up-to-date, the pom file should be updated to avoid confusion.

**Comment by RuedigerMoeller** [comment]
you are right. Thanks for reporting.

**Comment by RuedigerMoeller** [comment]
fixed. will be released with new version

**Comment by joey** [comment]
Thanks for the quick turnaround!
