### ISSUE TITLE
Android client compilation?

### ISSUE THREAD

**Issue by bradedelman** [RuedigerMoeller/fast-serialization#95]
Using the gradle dependency
    compile 'de.ruedigermoeller:fst:2.42'

I have fst running on Android. And it really is faster! Thanks!

I'd like to be able to build form source.  However, these dependencies don't seem to be part of the Android SDK: 
import sun.misc.Unsafe;
import sun.misc.Cleaner;
import sun.nio.ch.FileChannelImpl;
import sun.reflect.ReflectionFactory;

Given that the jar obtained by gradle works, it seems this is a problem you have solved.
Can you explain how to compile fst from source for Android?

Thanks!

**Comment by RuedigerMoeller** [comment]
I just build against standard JDK with -source 1.7. FST detects Android at
runtime and uses fallback implementations for the proprietary classes then.

2015-11-09 6:32 GMT+01:00 bradedelman <notifications@github.com>:

**Comment by bradedelman** [comment]
I see. Thanks.

**Comment by RuedigerMoeller** [comment]
hi there
reopen to serve as faq.
