### ISSUE TITLE
POM.xml outdated urls.

### ISSUE THREAD

**Issue by mafagafogigante** [RuedigerMoeller/fast-serialization#98]
Some stuff in the pom.xml file points to Google Code, and that seems to have been abandoned. No big deal, but could be updated. Just notifying you because I think you might have not seen that.

**Comment by RuedigerMoeller** [comment]
er .. i admit being a maven hater :)

**Comment by mafagafogigante** [comment]
If you want to assign it to me. Let the weekend come and I will submit the fixes. You deserve some help.

**Comment by mafagafogigante** [comment]
Also, I am OK with Maven so far.

**Comment by RuedigerMoeller** [comment]
any help is welcome, I am in the middle of a startup ..Actually maven has its good part, but I dislike the xml-buerocracy stuff ..

**Comment by mafagafogigante** [comment]
Congratulations! I hope it all works out well for you. I will do this if you want.

**Comment by mafagafogigante** [comment]
Unless your startup is evil. Then I hope you fail miserably.

**Comment by RuedigerMoeller** [comment]
I make you a collaborator then, but pls don't break stuff :), several projects directly rely on the trunk version

**Comment by RuedigerMoeller** [comment]
Ofc it will fail miserably, that's what startups are supposed to do ;)

**Comment by mafagafogigante** [comment]
I can already feel the power. It is taking over...

JK. I am a nice guy. Won't touch the master branch. I don't want the responsibility.

**Comment by RuedigerMoeller** [comment]
+1, going off now. good night

**Comment by mafagafogigante** [comment]
For you too.
